delete from FDR.FR_ARCHIVE_CTL where ARCT_ID IN(132,134,135,137,254,255,257,261,263);
Insert into FDR.FR_ARCHIVE_CTL
   (ARCT_ID, ARCT_SCHEMA_NAME, ARCT_TABLE_NAME, ARCT_ARC_SCHEMA_NAME, ARCT_ARC_TABLE_NAME, 
    ARCT_ARCHIVE, ARCT_ARCHIVE_DATE_COLUMN, ARCT_ARCHIVE_DAYS, ARCT_ARCHIVE_ORDER, ARCT_ARCHIVE_GROUP, 
    ARCT_GENERATE_SCRIPT_ONLY, ARCT_DATA_TRANSFER_METHOD)
 Values
   (132, 'SLR', 'SLR_JRNL_LINES', 'SLR', 'SLR_JRNL_LINES_ARC', 
    'Y', 'JL_EFFECTIVE_DATE', 390, 1100, 3, 
    'N', 'PARTITION+DML');
Insert into FDR.FR_ARCHIVE_CTL
   (ARCT_ID, ARCT_SCHEMA_NAME, ARCT_TABLE_NAME, ARCT_ARC_SCHEMA_NAME, ARCT_ARC_TABLE_NAME, 
    ARCT_ARCHIVE, ARCT_ARCHIVE_DATE_COLUMN, ARCT_ARCHIVE_DAYS, ARCT_ARCHIVE_ORDER, ARCT_ARCHIVE_GROUP, 
    ARCT_GENERATE_SCRIPT_ONLY, ARCT_DATA_TRANSFER_METHOD)
 Values
   (134, 'SLR', 'SLR_JRNL_LINE_ERRORS', 'SLR', 'SLR_JRNL_LINE_ERRORS_ARC', 
    'Y', 'JLE_CREATED_ON', 390, 1120, 3, 
    'N', 'DML');
Insert into FDR.FR_ARCHIVE_CTL
   (ARCT_ID, ARCT_SCHEMA_NAME, ARCT_TABLE_NAME, ARCT_ARC_SCHEMA_NAME, ARCT_ARC_TABLE_NAME, 
    ARCT_ARCHIVE, ARCT_ARCHIVE_DATE_COLUMN, ARCT_ARCHIVE_DAYS, ARCT_ARCHIVE_ORDER, ARCT_ARCHIVE_GROUP, 
    ARCT_GENERATE_SCRIPT_ONLY, ARCT_DATA_TRANSFER_METHOD)
 Values
   (135, 'SLR', 'SLR_JRNL_HEADERS', 'SLR', 'SLR_JRNL_HEADERS_ARC', 
    'Y', 'JH_JRNL_DATE', 390, 1130, 3, 
    'N', 'DML');
Insert into FDR.FR_ARCHIVE_CTL
   (ARCT_ID, ARCT_SCHEMA_NAME, ARCT_TABLE_NAME, ARCT_ARC_SCHEMA_NAME, ARCT_ARC_TABLE_NAME, 
    ARCT_ARCHIVE, ARCT_ARCHIVE_DATE_COLUMN, ARCT_ARCHIVE_DAYS, ARCT_ARCHIVE_ORDER, ARCT_ARCHIVE_GROUP, 
    ARCT_GENERATE_SCRIPT_ONLY, ARCT_DATA_TRANSFER_METHOD)
 Values
   (137, 'SLR', 'SLR_JOB_STATISTICS', 'SLR', 'SLR_JOB_STATISTICS_ARC', 
    'Y', 'JS_BUSINESS_DATE', 390, 1150, 3, 
    'N', 'DML');
Insert into FDR.FR_ARCHIVE_CTL
   (ARCT_ID, ARCT_SCHEMA_NAME, ARCT_TABLE_NAME, ARCT_ARC_SCHEMA_NAME, ARCT_ARC_TABLE_NAME, 
    ARCT_ARCHIVE, ARCT_ARCHIVE_DATE_COLUMN, ARCT_ARCHIVE_DAYS,ARCT_BEFORE_PROCESS_PROC,ARCT_ARCHIVE_WHERE_CLAUSE, ARCT_ARCHIVE_ORDER, 
    ARCT_ARCHIVE_GROUP, ARCT_GENERATE_SCRIPT_ONLY, ARCT_DATA_TRANSFER_METHOD, ARCT_ENTITY_COLUMN_NAME)
 Values
   (254, 'SLR', 'SLR_FAK_DAILY_BALANCES', 'SLR', 'SLR_FAK_DAILY_BALANCES_ARC', 
    'Y', 'FDB_BALANCE_DATE', 390,'PCUST_ROLLFAKBALANCESCUST','', 1200, 
    3, 'N', 'PARTITION+DML', 'FDB_ENTITY');
Insert into FDR.FR_ARCHIVE_CTL
   (ARCT_ID, ARCT_SCHEMA_NAME, ARCT_TABLE_NAME, ARCT_ARC_SCHEMA_NAME, ARCT_ARC_TABLE_NAME, 
    ARCT_ARCHIVE, ARCT_ARCHIVE_DATE_COLUMN, ARCT_ARCHIVE_DAYS,ARCT_BEFORE_PROCESS_PROC, ARCT_ARCHIVE_WHERE_CLAUSE, ARCT_ARCHIVE_ORDER, 
    ARCT_ARCHIVE_GROUP, ARCT_GENERATE_SCRIPT_ONLY, ARCT_DATA_TRANSFER_METHOD, ARCT_ENTITY_COLUMN_NAME)
 Values
   (255, 'SLR', 'SLR_EBA_DAILY_BALANCES', 'SLR', 'SLR_EBA_DAILY_BALANCES_ARC', 
    'Y', 'EDB_BALANCE_DATE', 390,'PCUST_ROLLEBABALANCESCUST','', 1220, 
    3, 'N', 'PARTITION+DML', 'EDB_ENTITY');
Insert into FDR.FR_ARCHIVE_CTL
   (ARCT_ID, ARCT_SCHEMA_NAME, ARCT_TABLE_NAME, ARCT_ARC_SCHEMA_NAME, ARCT_ARC_TABLE_NAME, 
    ARCT_ARCHIVE, ARCT_ARCHIVE_DATE_COLUMN, ARCT_ARCHIVE_DAYS, ARCT_ARCHIVE_WHERE_CLAUSE, ARCT_ARCHIVE_ORDER, 
    ARCT_ARCHIVE_GROUP, ARCT_GENERATE_SCRIPT_ONLY, ARCT_DATA_TRANSFER_METHOD)
 Values
   (257, 'SLR', 'SLR_LAST_BALANCES', 'PURGE', 'PURGE', 
    'Y', 'LB_GENERATED_FOR', 390, '', 1260, 
    3, 'N', 'PARTITION+DML');
Insert into FDR.FR_ARCHIVE_CTL
   (ARCT_ID, ARCT_SCHEMA_NAME, ARCT_TABLE_NAME, ARCT_ARC_SCHEMA_NAME, ARCT_ARC_TABLE_NAME, 
    ARCT_ARCHIVE, ARCT_ARCHIVE_DATE_COLUMN, ARCT_ARCHIVE_DAYS, ARCT_ARCHIVE_WHERE_CLAUSE, ARCT_ARCHIVE_ORDER, 
    ARCT_ARCHIVE_GROUP, ARCT_GENERATE_SCRIPT_ONLY, ARCT_DATA_TRANSFER_METHOD)
 Values
   (263, 'SLR', 'SLR_LAST_BALANCES_INDEX', 'PURGE', 'PURGE', 
    'Y', 'LBI_GENERATED_FOR', 390, '', 1305, 
    3, 'N', 'PARTITION+DML');
COMMIT;