DECLARE
  COUNT_INDEXES INTEGER;
BEGIN
  SELECT COUNT(*) INTO COUNT_INDEXES
    FROM USER_INDEXES
    WHERE upper(INDEX_NAME) = 'GC_EVENT_STATUS';

  IF COUNT_INDEXES > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX GC_EVENT_STATUS';
  END IF;

  SELECT COUNT(*) INTO COUNT_INDEXES
    FROM USER_INDEXES
    WHERE upper(INDEX_NAME) = 'IDXFR_STAN_RAW_GENERAL_CODES';

  IF COUNT_INDEXES > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX IDXFR_STAN_RAW_GENERAL_CODES';
  END IF;

END;
/
commit;
@@../aahCustom/aahStandardisation/src/main/db/indices/fdr/fr_stan_raw_general_codes.sql