DECLARE
    i INTEGER;
BEGIN

    SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name= 'IDX_CODE_ID_TYPE' and table_name = 'FR_GENERAL_CODES_AUD';
    
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX "FDR"."IDX_CODE_ID_TYPE" ON "FDR"."FR_GENERAL_CODES_AUD" ("GC_GENERAL_CODE_ID", "GC_GCT_CODE_TYPE_ID") TABLESPACE "FDR_DATA_IDX"';        
    END IF;
END;
/
