CREATE TABLE RDR.RR_GLINT_TO_SLR_AG
(
  RGJL_ID              NUMBER(18)               NOT NULL,
  JL_JRNL_HDR_ID       NUMBER(12)               NOT NULL,
  JL_JRNL_LINE_NUMBER  NUMBER(12)               NOT NULL
)
;

COMMENT ON TABLE RDR.RR_GLINT_TO_SLR_AG IS 'MAPS SLR JOURNALS GO GLINT JOURNALS';