create table stn.cession_link
(
    row_sid                  number ( 38 , 0 )                generated by default as identity not null
,   parent_stream_id         number ( 38 , 0 )                                                 not null
,   child_stream_id          number ( 38 , 0 )                                                 not null
,   link_typ                 varchar2 ( 30 char )                                              not null
,   lpg_id                   number ( 38 , 0 )     default 1                                   not null
,   event_status             varchar2 ( 1 char )   default 'U'                                 not null
,   feed_uuid                raw ( 16 )                                                        not null
,   no_retries               number ( 38 , 0 )     default 0                                   not null
,   step_run_sid             number ( 38 , 0 )     default 0                                   not null
,   constraint pk_cl         primary key ( row_sid )
,   constraint uk_cl         unique      ( parent_stream_id , child_stream_id , link_typ , feed_uuid )
,   constraint ck_stream_ids check       ( parent_stream_id != child_stream_id )
);