ALTER TABLE STN.CEV_VALID
 DROP PRIMARY KEY CASCADE;

DROP TABLE STN.CEV_VALID CASCADE CONSTRAINTS;

CREATE TABLE STN.CEV_VALID
(
  ROW_SID             NUMBER(38),
  CORRELATION_UUID    RAW(16),
  EVENT_ID            NUMBER(38),
  ACCOUNTING_DT       DATE,
  STREAM_ID           NUMBER(38),
  BASIS_CD            VARCHAR2(20 CHAR),
  PREMIUM_TYP         VARCHAR2(1 CHAR),
  BUSINESS_TYP        VARCHAR2(2 CHAR),
  EVENT_TYP           VARCHAR2(30 CHAR),
  BUSINESS_EVENT_TYP  VARCHAR2(50 CHAR),
  SOURCE_EVENT_TS     TIMESTAMP(6),
  TRANSACTION_CCY     VARCHAR2(3 CHAR),
  TRANSACTION_AMT     NUMBER(38,9),
  FUNCTIONAL_CCY      VARCHAR2(3 CHAR),
  FUNCTIONAL_AMT      NUMBER(38,9),
  REPORTING_CCY       VARCHAR2(3 CHAR),
  REPORTING_AMT       NUMBER(38,9),
  LPG_ID              NUMBER(38),
  EVENT_STATUS        VARCHAR2(1 CHAR),
  FEED_UUID           RAW(16),
  NO_RETRIES          NUMBER(38),
  STEP_RUN_SID        NUMBER(38),
  RECLASS_ENTITY      VARCHAR2(20 BYTE),
  ACCOUNT_CD          VARCHAR2(20 BYTE),
  CHARTFIELD_1        VARCHAR2(50 BYTE),
  JL_DESCRIPTION      VARCHAR2(100 BYTE)
)
TABLESPACE STN_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX STN.I_CEVV_UUID ON STN.CEV_VALID
(CORRELATION_UUID)
LOGGING
TABLESPACE STN_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX STN.PK_CEV_V ON STN.CEV_VALID
(ROW_SID)
LOGGING
TABLESPACE STN_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX STN.UK_CEV_V ON STN.CEV_VALID
(FEED_UUID, CORRELATION_UUID, ACCOUNTING_DT, STREAM_ID, BASIS_CD, 
PREMIUM_TYP, BUSINESS_TYP, EVENT_TYP)
LOGGING
TABLESPACE STN_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE STN.CEV_VALID ADD (
  CONSTRAINT PK_CEV_V
  PRIMARY KEY
  (ROW_SID)
  USING INDEX STN.PK_CEV_V
  ENABLE VALIDATE,
  CONSTRAINT UK_CEV_V
  UNIQUE (FEED_UUID, CORRELATION_UUID, ACCOUNTING_DT, STREAM_ID, BASIS_CD, PREMIUM_TYP, BUSINESS_TYP, EVENT_TYP)
  USING INDEX STN.UK_CEV_V
  ENABLE VALIDATE);

GRANT SELECT ON STN.CEV_VALID TO AAH_READ_ONLY;
