create table stn.feed
(
    feed_sid        number ( 38 , 0 )    generated by default as identity not null
,   feed_uuid       raw ( 16 )                                            not null
,   feed_typ        varchar2 ( 50 char )                                  not null
,   effective_dt    date                                                  not null
,   system_cd       varchar2 ( 50 char )                                  not null
,   stated_checksum varchar2 ( 100 char )                                 not null
,   loaded_ts       timestamp                                             not null
,   constraint pk_f     primary key ( feed_sid )
,   constraint uk_f     unique      ( feed_uuid )
,   constraint uk_f_tet unique      ( feed_typ , effective_dt , system_cd , loaded_ts )
,   constraint ck_feed_effective_dt check ( effective_dt = trunc ( effective_dt ) )
);