create table stn.legal_entity_ledger
(
    row_sid                 number   ( 38 , 0 )              generated by default as identity not null
,   le_cd                   varchar2 ( 20 char )                                              not null
,   ledger_cd               varchar2 ( 20 char )                                              not null
,   effective_from_dt       date                                                              not null
,   effective_to_dt         date                                                              not null
,   lpg_id                  number   ( 38 , 0 )  default 1                                    not null
,   event_status            varchar2 ( 1 char )  default 'U'                                  not null
,   feed_uuid               raw      ( 16 )                                                   not null
,   no_retries              number   ( 38 , 0 )  default 0                                    not null
,   step_run_sid            number   ( 38 , 0 )  default 0                                    not null
,   constraint pk_lel   primary key ( row_sid )
,   constraint uk_lel   unique      ( le_cd, ledger_cd, effective_from_dt, feed_uuid )
,   constraint ck_dates check       ( effective_from_dt < effective_to_dt )
);