create table stn.posting_accounting_basis
(
    basis_id                number ( 38 , 0 )    generated by default as identity not null
,   basis_cd                varchar2 ( 20 char )                                  not null
,   basis_typ               varchar2 ( 20 char )                                  not null
,   basis_grp               varchar2 ( 20 char )                                  not null
,   constraint pk_abasis       primary key ( basis_id )
,   constraint uk_abasis       unique      ( basis_cd )
,   constraint ck_ab_basis_typ check       ( basis_typ in ( 'STAT' , 'GAAP' ) )
);