CREATE OR REPLACE FORCE VIEW RDR.RRV_AG_FDR_ORG_HIERARCHY_TYPE AS 
SELECT
 OHT_ORG_HIER_TYPE_ID     
,OHT_ORG_HIER_TYPE_NAME  
,OHT_ORG_HIER_CLIENT_CODE
,OHT_ORG_HIER_CLASS      
,OHT_ACTIVE              
,OHT_INPUT_BY            
,OHT_AUTH_BY             
,OHT_AUTH_STATUS         
,OHT_INPUT_TIME          
,OHT_VALID_FROM          
,OHT_VALID_TO            
,OHT_DELETE_TIME         
FROM
   FDR.FR_ORG_HIERARCHY_TYPE ;
   