create or replace view rdr.rrv_ag_business_unit
as
select
 pl_party_legal_id          
,pl_cu_base_currency_id     
,pl_si_sys_inst_id          
,pl_ci_city_id              
,pl_co_country_incorp_id    
,pl_dty_netting_doc_type_id 
,pl_tx_tax_category_type_id 
,pl_co_country_resid_id     
,pl_full_legal_name         
,pl_pt_party_type_id        
,pl_party_legal_clicode     
,pl_human_short_name        
,pl_guarantor_legal_id      
,pl_market_sector           
,pl_ledger_code             
,pl_int_ext_flag            
,pl_finance_classification1 
,pl_finance_classification2 
,pl_group_classification    
,pl_group_sector            
,pl_collateralised          
,pl_nettable                
,pl_resident_flag           
,pl_equity_stock_code       
,pl_depot_position          
,pl_stock_market_cap        
,pl_active                  
,pl_input_by                
,pl_address_line1           
,pl_auth_by                 
,pl_address_line2           
,pl_address_line3           
,pl_auth_status             
,pl_input_time              
,pl_client_text1            
,pl_address_line4           
,pl_client_text2            
,pl_valid_from              
,pl_client_text3            
,pl_address_line5           
,pl_client_text4            
,pl_valid_to                
,pl_client_text5            
,pl_client_text6            
,pl_main_phone              
,pl_delete_time             
,pl_client_text7            
,pl_main_fax                
,pl_client_text8            
,pl_client_text9            
,pl_client_text10           
,pl_cred_rate_clicode       
,pl_co_country_of_risk_id   
,pl_global_id               
,pl_cu_local_currency_id    
,pl_primary_account_man     
,pl_local_account_man       
,pl_local_account_man_backup
,pl_trax_location           
,pl_predef_type             
from fdr.fr_party_legal
;
