create or replace view rdr.rrv_fr_posting_driver_ag
as
select
pd_posting_driver_id  
,pd_posting_schema     
,pd_aet_event_type     
,pd_sub_event          
,pd_amount_type        
,pd_posting_code       
,pd_dr_or_cr           
,pd_hopper             
,pd_field1             
,pd_field2             
,pd_transaction_no     
,pd_negate_flag1       
,pd_negate_flag2       
,pd_journal_type       
,pd_base_convert_flag  
,pd_local_convert_flag 
,pd_comment            
,pd_account_type       
,pd_valid_from         
,pd_valid_to           
,pd_active             
,pd_action             
,pd_input_by           
,pd_input_time         
,pd_delete_time        
,pd_auth_by            
,pd_auth_status        
,pd_client_type_1      
,pd_client_type_2      
,pd_client_type_3      
,pd_date_type          
,pd_currency_type      
,pd_book_type          
,pd_client_mapping_1   
,pd_client_mapping_2   
,pd_client_mapping_3   
,pd_keep_signage       
,pd_ret_recog_type_id  
from fdr.fr_posting_driver
;
