create or replace view rdr.rrv_insurance_policy_fx
as
select
LK_LOOKUP_KEY_ID         
,LK_LKT_LOOKUP_TYPE_CODE  
,LK_MATCH_KEY1            
,LK_MATCH_KEY2            
,LK_MATCH_KEY3            
,LK_MATCH_KEY4            
,LK_MATCH_KEY5            
,LK_MATCH_KEY6            
,LK_MATCH_KEY7            
,LK_MATCH_KEY8            
,LK_MATCH_KEY9            
,LK_MATCH_KEY10           
,LK_LOOKUP_VALUE1         
,LK_LOOKUP_VALUE2         
,LK_LOOKUP_VALUE3         
,LK_LOOKUP_VALUE4         
,LK_LOOKUP_VALUE5         
,LK_LOOKUP_VALUE6         
,LK_LOOKUP_VALUE7         
,LK_LOOKUP_VALUE8         
,LK_LOOKUP_VALUE9         
,LK_LOOKUP_VALUE10        
,LK_VALID_FROM            
,LK_VALID_TO              
,LK_INPUT_BY              
,LK_INPUT_TIME            
,LK_AUTH_BY               
,LK_AUTH_STATUS           
,LK_DELETE_TIME           
,LK_ACTIVE     
,LPG_ID        
,LK_EFFECTIVE_FROM   
,LK_EFFECTIVE_TO
from fdr.fr_general_lookup
;