create global temporary table slr.slr_fak_bop_amounts_tmp2
(
	FDB_FAK_ID VARCHAR2(32) NOT NULL ENABLE,
	FDB_BALANCE_DATE DATE NOT NULL ENABLE,
	FDB_BALANCE_TYPE NUMBER(2,0) NOT NULL ENABLE,
	FDB_ENTITY VARCHAR2(20 BYTE) NOT NULL ENABLE,
	FDB_EPG_ID VARCHAR2(18 BYTE) NOT NULL ENABLE,
	FDB_ID VARCHAR2(100 BYTE) NOT NULL ENABLE
)
on commit preserve rows;