create global temporary table slr.slr_eba_bop_amounts_tmp2
(
	EDB_FAK_ID VARCHAR2(32) NOT NULL ENABLE,
	EDB_EBA_ID VARCHAR2(32) NOT NULL ENABLE,
	EDB_BALANCE_DATE DATE NOT NULL ENABLE,
	EDB_BALANCE_TYPE NUMBER(2,0) NOT NULL ENABLE,
	EDB_ENTITY VARCHAR2(20 BYTE) NOT NULL ENABLE,
	EDB_EPG_ID VARCHAR2(18 BYTE) NOT NULL ENABLE,
	EDB_ID VARCHAR2(110 BYTE) NOT NULL ENABLE
)
on commit preserve rows;