grant select on fdr.fr_combination_check_error to rdr;
grant insert on fdr.fr_combination_check_error to rdr;
grant delete on fdr.fr_combination_check_error to rdr;
grant select on fdr.fr_combination_check_error to slr;
grant insert on fdr.fr_combination_check_error to slr;
grant delete on fdr.fr_combination_check_error to slr;
grant select on fdr.fr_combination_check_error to gui;
grant insert on fdr.fr_combination_check_error to gui;
grant delete on fdr.fr_combination_check_error to gui;