@@../aahCustom/aahStandardisation/src/main/db/tables/stn/load_fr_account_lookup.sql
@@../aahCustom/aahStandardisation/src/main/db/tables/stn/posting_account_derivation.sql
@@../aahCustom/aahStandardisation/src/main/db/tables/stn/vie_posting_account_derivation.sql
@@../aahCustom/aahStandardisation/src/main/db/tables/stn/cev_vie_data.sql
@@../aahCustom/aahStandardisation/src/main/db/tables/stn/cev_intercompany_data.sql
@@../aahCustom/aahStandardisation/src/main/db/tables/stn/cev_non_intercompany_data.sql
@@../aahCustom/aahStandardisation/src/main/db/tables/stn/cev_data.sql
@@../aahCustom/aahStandardisation/src/main/db/tables/stn/cev_valid.sql
@@../aahCustom/aahStandardisation/src/main/db/tables/stn/cev_mtm_data.sql
@@../aahCustom/aahStandardisation/src/main/db/tables/stn/cev_gaap_fut_accts_data.sql