UPDATE STN.VIE_POSTING_METHOD_LEDGER SET NEGATE_FLAG = '-1'
WHERE INPUT_BASIS_ID = '1'
    AND EVENT_TYP_ID = '215'
    AND VIE_EVENT_TYP_ID = '207'
    AND NEGATE_FLAG = '1';
COMMIT;

declare
  count_records integer;
begin
  select count(*) into count_records
    from STN.VIE_POSTING_METHOD_LEDGER
where INPUT_BASIS_ID = '2' and EVENT_TYP_ID = '215';
    
  if count_records = 0 then

	INSERT INTO STN.VIE_POSTING_METHOD_LEDGER (INPUT_BASIS_ID,EVENT_TYP_ID,VIE_ID,VIE_EVENT_TYP_ID,OUTPUT_BASIS_ID,LEDGER_ID,FIN_CALC_ID,NEGATE_FLAG,SUB_EVENT) VALUES (2,215,5,207,1,4,6,1,'DECONSOL');
	INSERT INTO STN.VIE_POSTING_METHOD_LEDGER (INPUT_BASIS_ID,EVENT_TYP_ID,VIE_ID,VIE_EVENT_TYP_ID,OUTPUT_BASIS_ID,LEDGER_ID,FIN_CALC_ID,NEGATE_FLAG,SUB_EVENT) VALUES (2,215,6,207,1,4,6,1,'NULL');
	INSERT INTO STN.VIE_POSTING_METHOD_LEDGER (INPUT_BASIS_ID,EVENT_TYP_ID,VIE_ID,VIE_EVENT_TYP_ID,OUTPUT_BASIS_ID,LEDGER_ID,FIN_CALC_ID,NEGATE_FLAG,SUB_EVENT) VALUES (2,215,2,207,1,4,6,1,'NULL');
	COMMIT;

  end if;  
end;
/

UPDATE STN.VIE_POSTING_METHOD_LEDGER SET NEGATE_FLAG = '-1'
WHERE INPUT_BASIS_ID = '1'
    AND EVENT_TYP_ID = '14'
    AND VIE_EVENT_TYP_ID = '131'
    AND NEGATE_FLAG = '1';
COMMIT;

declare
  count_records integer;
begin
  select count(*) into count_records
    from STN.VIE_POSTING_METHOD_LEDGER
where INPUT_BASIS_ID = '2' and EVENT_TYP_ID = '14';
    
  if count_records = 0 then

	INSERT INTO STN.VIE_POSTING_METHOD_LEDGER (INPUT_BASIS_ID,EVENT_TYP_ID,VIE_ID,VIE_EVENT_TYP_ID,OUTPUT_BASIS_ID,LEDGER_ID,FIN_CALC_ID,NEGATE_FLAG,SUB_EVENT) VALUES (2,14,5,131,1,4,6,1,'DECONSOL');
	INSERT INTO STN.VIE_POSTING_METHOD_LEDGER (INPUT_BASIS_ID,EVENT_TYP_ID,VIE_ID,VIE_EVENT_TYP_ID,OUTPUT_BASIS_ID,LEDGER_ID,FIN_CALC_ID,NEGATE_FLAG,SUB_EVENT) VALUES (2,14,6,131,1,4,6,1,'NULL');
	INSERT INTO STN.VIE_POSTING_METHOD_LEDGER (INPUT_BASIS_ID,EVENT_TYP_ID,VIE_ID,VIE_EVENT_TYP_ID,OUTPUT_BASIS_ID,LEDGER_ID,FIN_CALC_ID,NEGATE_FLAG,SUB_EVENT) VALUES (2,14,2,131,1,4,6,1,'NULL');
	COMMIT;

  end if;  
end;
/ 


UPDATE STN.VIE_POSTING_METHOD_LEDGER SET SUB_EVENT = 'NULL'
WHERE FIN_CALC_ID = '6'
    AND SUB_EVENT = 'DECONSOL'
    AND VIE_ID = '5';
COMMIT;

declare
  count_records integer;
begin
  select count(*) into count_records
    from STN.VIE_POSTING_METHOD_LEDGER
where FIN_CALC_ID = '6'
		AND SUB_EVENT = 'NULL'
		AND VIE_ID = '3';
    
  if count_records = 0 then

	INSERT INTO STN.VIE_POSTING_METHOD_LEDGER
	SELECT
		INPUT_BASIS_ID, EVENT_TYP_ID, '3', VIE_EVENT_TYP_ID, OUTPUT_BASIS_ID, LEDGER_ID, FIN_CALC_ID, NEGATE_FLAG, SUB_EVENT
	FROM STN.VIE_POSTING_METHOD_LEDGER
	WHERE FIN_CALC_ID = '6'
		AND SUB_EVENT = 'NULL'
		AND VIE_ID = '5';
	COMMIT;

  end if;  
end;
/ 


declare
  count_records integer;
begin
  select count(*) into count_records
    from STN.VIE_POSTING_METHOD_LEDGER
where FIN_CALC_ID = '6'
		AND SUB_EVENT = 'NULL'
		AND VIE_ID = '4';
    
  if count_records = 0 then

	INSERT INTO STN.VIE_POSTING_METHOD_LEDGER
	SELECT
		INPUT_BASIS_ID, EVENT_TYP_ID, '4', VIE_EVENT_TYP_ID, OUTPUT_BASIS_ID, LEDGER_ID, FIN_CALC_ID, NEGATE_FLAG, SUB_EVENT
	FROM STN.VIE_POSTING_METHOD_LEDGER
	WHERE FIN_CALC_ID = '6'
		AND SUB_EVENT = 'NULL'
		AND VIE_ID = '5';
	COMMIT;

  end if;  
end;
/ 