DROP VIEW RDR.RRV_AG_POSTING_DRIVER_AUD;

/* Formatted on 10/03/2024 10:08:17 AM (QP5 v5.252.13127.32847) */
CREATE OR REPLACE FORCE VIEW RDR.RRV_AG_POSTING_DRIVER_AUD
(
   PD_AUD_ID,
   PD_REP_SCHEMA_UPD,
   PD_POSTING_DRIVER_ID,
   PD_POSTING_SCHEMA,
   PD_AET_EVENT_TYPE,
   PD_SUB_EVENT,
   PD_AMOUNT_TYPE,
   PD_POSTING_CODE,
   PD_DR_OR_CR,
   PD_HOPPER,
   PD_FIELD1,
   PD_FIELD2,
   PD_TRANSACTION_NO,
   PD_NEGATE_FLAG1,
   PD_NEGATE_FLAG2,
   PD_JOURNAL_TYPE,
   PD_BASE_CONVERT_FLAG,
   PD_LOCAL_CONVERT_FLAG,
   PD_COMMENT,
   PD_ACCOUNT_TYPE,
   PD_VALID_FROM,
   PD_VALID_TO,
   PD_ACTIVE,
   PD_ACTION,
   PD_INPUT_BY,
   PD_INPUT_TIME,
   PD_DELETE_TIME,
   PD_AUTH_BY,
   PD_AUTH_STATUS,
   PD_CLIENT_TYPE_1,
   PD_CLIENT_TYPE_2,
   PD_CLIENT_TYPE_3,
   PD_DATE_TYPE,
   PD_CURRENCY_TYPE,
   PD_BOOK_TYPE,
   PD_CLIENT_MAPPING_1,
   PD_CLIENT_MAPPING_2,
   PD_CLIENT_MAPPING_3,
   PD_KEEP_SIGNAGE,
   PD_RET_RECOG_TYPE_ID,
   PD_UPDATE_TIME
)
   BEQUEATH DEFINER
AS
   SELECT pd_aud_id,
          pd_rep_schema_upd,
          pd_posting_driver_id,
          pd_posting_schema,
          pd_aet_event_type,
          pd_sub_event,
          pd_amount_type,
          pd_posting_code,
          pd_dr_or_cr,
          pd_hopper,
          pd_field1,
          pd_field2,
          pd_transaction_no,
          pd_negate_flag1,
          pd_negate_flag2,
          pd_journal_type,
          pd_base_convert_flag,
          pd_local_convert_flag,
          pd_comment,
          pd_account_type,
          pd_valid_from,
          pd_valid_to,
          pd_active,
          pd_action,
          pd_input_by,
          pd_input_time,
          pd_delete_time,
          pd_auth_by,
          pd_auth_status,
          pd_client_type_1,
          pd_client_type_2,
          pd_client_type_3,
          pd_date_type,
          pd_currency_type,
          pd_book_type,
          pd_client_mapping_1,
          pd_client_mapping_2,
          pd_client_mapping_3,
          pd_keep_signage,
          pd_ret_recog_type_id,
          pd_update_time
     FROM fdr.fr_posting_driver_aud;


GRANT SELECT ON RDR.RRV_AG_POSTING_DRIVER_AUD TO AAH_RDR;

GRANT SELECT ON RDR.RRV_AG_POSTING_DRIVER_AUD TO AAH_READ_ONLY;
