DECLARE
    i INTEGER;
    j INTEGER;
    x INTEGER;    
BEGIN
    SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'BAK_XPK_RR_GLINT_TO_SLR_AG';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'ALTER INDEX XPK_RR_GLINT_TO_SLR_AG RENAME TO BAK_XPK_RR_GLINT_TO_SLR_AG';
    END IF;

    SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'BAK_IDX_RR_GLINT_TO_SLR_AG_HDR';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'ALTER INDEX IDX_RR_GLINT_TO_SLR_AG_HDR RENAME TO BAK_IDX_RR_GLINT_TO_SLR_AG_HDR';
    END IF;         

    SELECT COUNT(*) INTO i FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'BAK_XPK_RR_GLINT_TO_SLR_AG';
    SELECT COUNT(*) INTO x FROM user_indexes WHERE index_name = 'BAK_XPK_RR_GLINT_TO_SLR_AG';
    IF i = 0 AND x = 0 THEN
        select COUNT(*) into j from tab where tname = 'RR_GLINT_TO_SLR_AG';
        IF j = 0 THEN
            EXECUTE IMMEDIATE 'CREATE TABLE RDR.RR_GLINT_TO_SLR_AG (RGJL_ID NUMBER(18) NOT NULL,JL_JRNL_HDR_ID CHAR(32 BYTE) NOT NULL,JL_JRNL_LINE_NUMBER NUMBER(12) NOT NULL)';                        
        END IF;                
        SELECT COUNT(*) INTO i FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'XPK_RR_GLINT_TO_SLR_AG';
        IF i = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE RDR.RR_GLINT_TO_SLR_AG ADD (CONSTRAINT XPK_RR_GLINT_TO_SLR_AG PRIMARY KEY (RGJL_ID, JL_JRNL_HDR_ID, JL_JRNL_LINE_NUMBER) ENABLE VALIDATE)';
        END IF;        
        EXECUTE IMMEDIATE 'ALTER TABLE RR_GLINT_TO_SLR_AG RENAME CONSTRAINT XPK_RR_GLINT_TO_SLR_AG TO BAK_XPK_RR_GLINT_TO_SLR_AG';
    END IF;       

   
    select COUNT(*) into i from tab where tname = 'BAK_RR_GLINT_TO_SLR_AG';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE RR_GLINT_TO_SLR_AG RENAME TO BAK_RR_GLINT_TO_SLR_AG';
    END IF;

   
    select COUNT(*) into i from tab where tname = 'RR_GLINT_TO_SLR_AG';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE RR_GLINT_TO_SLR_AG (RGJL_ID NOT NULL,JL_JRNL_HDR_ID NOT NULL,JL_JRNL_LINE_NUMBER NOT NULL) AS SELECT RGJL_ID,CAST(STANDARD_HASH(TO_CHAR(JL_JRNL_HDR_ID), ''MD5'') AS CHAR(32)) AS JL_JRNL_HDR_ID, JL_JRNL_LINE_NUMBER FROM BAK_RR_GLINT_TO_SLR_AG';
    END IF;
    
    SELECT COUNT(*) INTO i FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'XPK_RR_GLINT_TO_SLR_AG';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE RR_GLINT_TO_SLR_AG ADD CONSTRAINT XPK_RR_GLINT_TO_SLR_AG PRIMARY KEY (RGJL_ID, JL_JRNL_HDR_ID, JL_JRNL_LINE_NUMBER)';
    END IF;

    SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'XPK_RR_GLINT_TO_SLR_AG';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE RR_GLINT_TO_SLR_AG ADD CONSTRAINT XPK_RR_GLINT_TO_SLR_AG PRIMARY KEY (RGJL_ID, JL_JRNL_HDR_ID, JL_JRNL_LINE_NUMBER)';
    END IF;  

    SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'IDX_RR_GLINT_TO_SLR_AG_HDR';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX IDX_RR_GLINT_TO_SLR_AG_HDR ON RR_GLINT_TO_SLR_AG (JL_JRNL_HDR_ID, JL_JRNL_LINE_NUMBER)';
    END IF;  
    
END;
/



