ALTER INDEX XPK_RR_GLINT_TO_SLR_AG RENAME TO BAK_XPK_RR_GLINT_TO_SLR_AG;
ALTER INDEX IDX_RR_GLINT_TO_SLR_AG_HDR RENAME TO BAK_IDX_RR_GLINT_TO_SLR_AG_HDR;
ALTER TABLE RR_GLINT_TO_SLR_AG RENAME CONSTRAINT XPK_RR_GLINT_TO_SLR_AG TO BAK_XPK_RR_GLINT_TO_SLR_AG;
ALTER TABLE RR_GLINT_TO_SLR_AG RENAME TO BAK_RR_GLINT_TO_SLR_AG;

CREATE TABLE RR_GLINT_TO_SLR_AG (
  RGJL_ID NOT NULL,
  JL_JRNL_HDR_ID NOT NULL,
  JL_JRNL_LINE_NUMBER NOT NULL
) AS
SELECT RGJL_ID,
       CAST(STANDARD_HASH(TO_CHAR(JL_JRNL_HDR_ID), 'MD5') AS CHAR(32)) AS JL_JRNL_HDR_ID,
       JL_JRNL_LINE_NUMBER
FROM BAK_RR_GLINT_TO_SLR_AG;

ALTER TABLE RR_GLINT_TO_SLR_AG ADD CONSTRAINT XPK_RR_GLINT_TO_SLR_AG PRIMARY KEY (RGJL_ID, JL_JRNL_HDR_ID, JL_JRNL_LINE_NUMBER);
CREATE UNIQUE INDEX IDX_RR_GLINT_TO_SLR_AG_HDR ON RR_GLINT_TO_SLR_AG (JL_JRNL_HDR_ID, JL_JRNL_LINE_NUMBER);
