ALTER INDEX XPK_GLINT_JOURNAL_LINE RENAME TO BAK_XPK_GLINT_JOURNAL_LINE;
ALTER INDEX IDX_AG_GLINT_JE_LINE01 RENAME TO BAK_IDX_AG_GLINT_JE_LINE01;
ALTER INDEX XIF1GL_INTERFACE_JOURNAL_LINE RENAME TO BAK_XIF1GL_INTERFACE_JOURNAL_LINE;
ALTER TABLE RR_GLINT_JOURNAL_LINE RENAME CONSTRAINT GLINT_J_JL TO BAK_GLINT_J_JL;
ALTER TABLE RR_GLINT_JOURNAL_LINE RENAME CONSTRAINT XPK_GLINT_JOURNAL_LINE TO BAK_XPK_GLINT_JOURNAL_LINE;
ALTER TABLE RR_GLINT_JOURNAL_LINE RENAME TO BAK_RR_GLINT_JOURNAL_LINE;

CREATE TABLE RR_GLINT_JOURNAL_LINE (
  RGJL_ID NOT NULL,
  RGJL_RGJ_ID NOT NULL,
  RGJL_RGJ_RGBC_ID NOT NULL,
  RGJL_AAH_JOURNAL,
  RGJL_AAH_JOURNAL_LINE,
  INPUT_TIME DEFAULT SYSDATE NOT NULL,
  INPUT_USER DEFAULT USER NOT NULL,
  MODIFIED_TIME DEFAULT SYSDATE NOT NULL,
  MODIFIED_USER DEFAULT USER NOT NULL,
  GL_DISTRIB_STATUS NOT NULL,
  APPL_JRNL_ID NOT NULL,
  BUSINESS_UNIT_GL NOT NULL,
  BUSINESS_UNIT NOT NULL,
  LEDGER_GROUP NOT NULL,
  LEDGER NOT NULL,
  JOURNAL_ID NOT NULL,
  JOURNAL_DATE,
  JOURNAL_LINE NOT NULL,
  ACCOUNTING_DT,
  FISCAL_YEAR NOT NULL,
  ACCOUNTING_PERIOD NOT NULL,
  FOREIGN_CURRENCY NOT NULL,
  FOREIGN_AMOUNT NOT NULL,
  CURRENCY_CD NOT NULL,
  MONETARY_AMOUNT NOT NULL,
  ACCOUNT NOT NULL,
  DEPTID NOT NULL,
  PRODUCT NOT NULL,
  AFFILIATE NOT NULL,
  PROGRAM_CODE NOT NULL,
  CHARTFIELD1 NOT NULL,
  LINE_DESCR NOT NULL,
  JRNL_LN_REF NOT NULL,
  PROCESS_INSTANCE NOT NULL,
  NOTES_254 NOT NULL,
  DTTM_STAMP,
  EVENT_CLASS NOT NULL,
  AAH_JRNL_HDR_NBR NOT NULL,
  CREDIT_AMT,
  DEBIT_AMT,
  EVENT_STATUS NOT NULL,
  SLR_PROCESS_ID NOT NULL,
  MANUAL_JE NOT NULL,
  PS_FILTER NOT NULL,
  JH_JRNL_TYPE NOT NULL,
  JH_JRNL_DESCRIPTION NOT NULL
) AS
SELECT  RGJL_ID,
        RGJL_RGJ_ID,
        RGJL_RGJ_RGBC_ID,
        RGJL_AAH_JOURNAL,
        RGJL_AAH_JOURNAL_LINE,
        INPUT_TIME,
        INPUT_USER,
        MODIFIED_TIME,
        MODIFIED_USER,
        GL_DISTRIB_STATUS,
        APPL_JRNL_ID,
        BUSINESS_UNIT_GL,
        BUSINESS_UNIT,
        LEDGER_GROUP,
        LEDGER,
        JOURNAL_ID,
        JOURNAL_DATE,
        JOURNAL_LINE,
        ACCOUNTING_DT,
        FISCAL_YEAR,
        ACCOUNTING_PERIOD,
        FOREIGN_CURRENCY,
        FOREIGN_AMOUNT,
        CURRENCY_CD,
        MONETARY_AMOUNT,
        ACCOUNT,
        DEPTID,
        PRODUCT,
        AFFILIATE,
        PROGRAM_CODE,
        CHARTFIELD1,
        LINE_DESCR,
        JRNL_LN_REF,
        PROCESS_INSTANCE,
        NOTES_254,
        DTTM_STAMP,
        EVENT_CLASS,
        CAST(STANDARD_HASH(TO_CHAR(AAH_JRNL_HDR_NBR), 'MD5') AS CHAR(32)) AS AAH_JRNL_HDR_NBR,
        CREDIT_AMT,
        DEBIT_AMT,
        EVENT_STATUS,
        SLR_PROCESS_ID,
        MANUAL_JE,
        PS_FILTER,
        JH_JRNL_TYPE,
        JH_JRNL_DESCRIPTION
FROM BAK_RR_GLINT_JOURNAL_LINE;

ALTER TABLE RR_GLINT_JOURNAL_LINE ADD CONSTRAINT XPK_GLINT_JOURNAL_LINE PRIMARY KEY (RGJL_ID);
ALTER TABLE RR_GLINT_JOURNAL_LINE ADD CONSTRAINT GLINT_J_JL FOREIGN KEY (RGJL_RGJ_RGBC_ID, RGJL_RGJ_ID) REFERENCES RR_GLINT_JOURNAL (RGJ_RGBC_ID, RGJ_ID);
CREATE INDEX IDX_AG_GLINT_JE_LINE01 ON RR_GLINT_JOURNAL_LINE (PS_FILTER);
CREATE INDEX XIF1GL_INTERFACE_JOURNAL_LINE ON RR_GLINT_JOURNAL_LINE (RGJL_RGJ_ID, RGJL_RGJ_RGBC_ID);

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.RGJL_ID IS 'The unique identifier for the journal line.
Core Column.';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.RGJL_RGJ_ID IS 'The Journal Identifier as it will appear in the GL (RR_GLINT_JOURNAL).
Core Column.';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.RGJL_RGJ_RGBC_ID IS 'The unique batch identifier (RR_GLINT_BATCH_CONTROL).
Core Column.';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.RGJL_AAH_JOURNAL IS 'If this line has been directly mapped from a SLR Journal Line, then this will be populated with the SLR Journal Identifier.
Core Column.';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.RGJL_AAH_JOURNAL_LINE IS 'If this line has been directly mapped from a SLR Journal Line, then this will be populated with the SLR Journal Line Number.
Core Column.';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.INPUT_TIME IS 'Date/Time the record was first inserted.
Core Column.';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.INPUT_USER IS 'User/Process that created the record.
Core Column.';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.MODIFIED_TIME IS 'Date/Time the record was last updated.
Core Column.';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.MODIFIED_USER IS 'User/Process that last updated the record.
Core Column.';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.GL_DISTRIB_STATUS IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.APPL_JRNL_ID IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.BUSINESS_UNIT_GL IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.BUSINESS_UNIT IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.LEDGER_GROUP IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.LEDGER IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.JOURNAL_ID IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.JOURNAL_DATE IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.JOURNAL_LINE IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.ACCOUNTING_DT IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.FISCAL_YEAR IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.ACCOUNTING_PERIOD IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.FOREIGN_CURRENCY IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.FOREIGN_AMOUNT IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.CURRENCY_CD IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.MONETARY_AMOUNT IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.ACCOUNT IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.DEPTID IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.PRODUCT IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.AFFILIATE IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.PROGRAM_CODE IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.CHARTFIELD1 IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.LINE_DESCR IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.JRNL_LN_REF IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.PROCESS_INSTANCE IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.NOTES_254 IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.DTTM_STAMP IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.EVENT_CLASS IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.AAH_JRNL_HDR_NBR IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.CREDIT_AMT IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.DEBIT_AMT IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.EVENT_STATUS IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.MANUAL_JE IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.PS_FILTER IS 'Custom Column to restrict data in link';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.JH_JRNL_TYPE IS 'Custom Column';
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.JH_JRNL_DESCRIPTION IS 'Custom Column';
COMMENT ON TABLE RDR.RR_GLINT_JOURNAL_LINE  IS 'Stores each of the journal lines that is to be sent to the GL.
Amend the custom columns within this table (and RR_GLINT_TEMP_JOURNAL_LINE) according to the specific General Ledger that is used. The default custom column list is for an Oracle GL.';
