DROP TABLE RR_GLINT_SUSPENSE_LINE;

CREATE GLOBAL TEMPORARY TABLE RDR.RR_GLINT_SUSPENSE_LINE 
(
  JL_JRNL_HDR_ID NUMBER(12,0), 
  JL_JRNL_LINE_NUMBER NUMBER(12,0), 
  JL_EPG_ID VARCHAR2(18 BYTE), 
  JL_EFFECTIVE_DATE DATE, 
  JL_SUSPENSE_ID NUMBER(12,0), 
  JL_ENTITY VARCHAR2(20 BYTE), 
  JL_ACCOUNT VARCHAR2(20 BYTE), 
  JL_SEGMENT_1 VARCHAR2(100 BYTE), 
  JL_SEGMENT_2 VARCHAR2(100 BYTE), 
  JL_SEGMENT_3 VARCHAR2(100 BYTE), 
  JL_SEGMENT_4 VARCHAR2(100 BYTE), 
  JL_SEGMENT_5 VARCHAR2(100 BYTE), 
  JL_SEGMENT_6 VARCHAR2(100 BYTE), 
  JL_SEGMENT_7 VARCHAR2(100 BYTE), 
  JL_SEGMENT_8 VARCHAR2(100 BYTE), 
  JL_SEGMENT_9 VARCHAR2(100 BYTE), 
  JL_SEGMENT_10 VARCHAR2(100 BYTE), 
  JL_ATTRIBUTE_1 VARCHAR2(100 BYTE), 
  JL_ATTRIBUTE_2 VARCHAR2(100 BYTE), 
  JL_ATTRIBUTE_3 VARCHAR2(100 BYTE), 
  JL_ATTRIBUTE_4 VARCHAR2(100 BYTE), 
  JL_ATTRIBUTE_5 VARCHAR2(100 BYTE), 
  JL_REFERENCE_1 VARCHAR2(100 BYTE), 
  JL_REFERENCE_2 VARCHAR2(100 BYTE), 
  JL_REFERENCE_3 VARCHAR2(100 BYTE), 
  JL_REFERENCE_4 VARCHAR2(100 BYTE), 
  JL_REFERENCE_5 VARCHAR2(100 BYTE), 
  JL_REFERENCE_6 VARCHAR2(100 BYTE), 
  JL_REFERENCE_7 VARCHAR2(100 BYTE), 
  JL_REFERENCE_8 VARCHAR2(100 BYTE), 
  JL_REFERENCE_9 VARCHAR2(100 BYTE), 
  JL_REFERENCE_10 VARCHAR2(100 BYTE), 
  PRIMARY KEY (JL_JRNL_HDR_ID, JL_JRNL_LINE_NUMBER) ENABLE
) ON COMMIT DELETE ROWS ;

COMMENT ON TABLE RDR.RR_GLINT_SUSPENSE_LINE  IS 'Temporary table to hold the AAH journal lines that failed combination checking with the relevant values replaced with their suspense equivalents.';
