CREATE GLOBAL TEMPORARY TABLE SLR.SLR_FAK_BOP_AMOUNTS_TMP
(
	FDB_FAK_ID VARCHAR2(32) NOT NULL ENABLE,
	FDB_BALANCE_DATE DATE NOT NULL ENABLE,
	FDB_BALANCE_TYPE NUMBER(3,0) NOT NULL ENABLE,
	FDB_TRAN_BOP_MTD_BALANCE NUMBER(33,3),
	FDB_TRAN_BOP_QTD_BALANCE NUMBER(33,3),
	FDB_TRAN_BOP_YTD_BALANCE NUMBER(33,3),
	FDB_BASE_BOP_MTD_BALANCE NUMBER(33,3),
	FDB_BASE_BOP_QTD_BALANCE NUMBER(33,3),
	FDB_BASE_BOP_YTD_BALANCE NUMBER(33,3),
	FDB_LOCAL_BOP_MTD_BALANCE NUMBER(33,3),
	FDB_LOCAL_BOP_QTD_BALANCE NUMBER(33,3),
	FDB_LOCAL_BOP_YTD_BALANCE NUMBER(33,3),
	FDB_PERIOD_MONTH NUMBER(2,0) NOT NULL ENABLE,
	FDB_PERIOD_QTR NUMBER(1,0) NOT NULL ENABLE,
	FDB_PERIOD_YEAR NUMBER(4,0) NOT NULL ENABLE,
	FDB_PERIOD_LTD NUMBER(2,0) NOT NULL ENABLE,
	FDB_AMENDED_ON DATE NOT NULL ENABLE
) ON COMMIT PRESERVE ROWS;

CREATE INDEX SLR.IDX_FAK_BOP_AMOUNTS_TMP_01 ON SLR.SLR_FAK_BOP_AMOUNTS_TMP (FDB_FAK_ID, FDB_BALANCE_DATE);
