CREATE GLOBAL TEMPORARY TABLE SLR.SLR_FAK_BOP_AMOUNTS_TMP2
(
	FDB_FAK_ID VARCHAR2(32) NOT NULL ENABLE,
	FDB_BALANCE_DATE DATE NOT NULL ENABLE,
	FDB_BALANCE_TYPE NUMBER(2,0) NOT NULL ENABLE,
	FDB_ENTITY VARCHAR2(20 BYTE) NOT NULL ENABLE,
	FDB_EPG_ID VARCHAR2(18 BYTE) NOT NULL ENABLE,
	FDB_ID VARCHAR2(100 BYTE) NOT NULL ENABLE
) ON COMMIT PRESERVE ROWS;

CREATE INDEX SLR.IDX_FAK_BOP_AMOUNTS_TMP2_01 ON SLR.SLR_FAK_BOP_AMOUNTS_TMP2 (FDB_FAK_ID, FDB_BALANCE_DATE);
