CREATE GLOBAL TEMPORARY TABLE SLR.SLR_FAK_BOP_AMOUNTS_TMP3
(
	FDB_FAK_ID VARCHAR2(32) NOT NULL ENABLE,
	FDB_BALANCE_DATE DATE NOT NULL ENABLE,
	FDB_BALANCE_TYPE NUMBER(3,0) NOT NULL ENABLE,
	FDB_TRAN_DAILY_MOVEMENT NUMBER(33,3),
	FDB_TRAN_MTD_BALANCE NUMBER(33,3),
	FDB_TRAN_YTD_BALANCE NUMBER(33,3),
	FDB_TRAN_LTD_BALANCE NUMBER(33,3),
	FDB_BASE_DAILY_MOVEMENT NUMBER(33,3),
	FDB_BASE_MTD_BALANCE NUMBER(33,3),
	FDB_BASE_YTD_BALANCE NUMBER(33,3),
	FDB_BASE_LTD_BALANCE NUMBER(33,3),
	FDB_LOCAL_DAILY_MOVEMENT NUMBER(33,3),
	FDB_LOCAL_MTD_BALANCE NUMBER(33,3),
	FDB_LOCAL_YTD_BALANCE NUMBER(33,3),
	FDB_LOCAL_LTD_BALANCE NUMBER(33,3),
	FDB_PERIOD_MONTH NUMBER(2,0) NOT NULL ENABLE,
	FDB_PERIOD_QTR NUMBER(1,0) NOT NULL ENABLE,
	FDB_PERIOD_YEAR NUMBER(4,0) NOT NULL ENABLE,
	FDB_PERIOD_LTD NUMBER(2,0) NOT NULL ENABLE,
	FDB_PROCESS_ID NUMBER(30,0) NOT NULL ENABLE,
	FDB_AMENDED_ON DATE NOT NULL ENABLE,
	FDB_ENTITY VARCHAR2(20 BYTE) NOT NULL ENABLE,
	FDB_EPG_ID VARCHAR2(18 BYTE) NOT NULL ENABLE,
	FDB_ID VARCHAR2(100 BYTE) NOT NULL ENABLE,
	YEAR_MTH VARCHAR2(6 BYTE),
	YEAR_QTR VARCHAR2(5 BYTE),
	YEAR VARCHAR2(4 BYTE),
	LAST_IN_YR VARCHAR2(2 BYTE)
   ) ON COMMIT PRESERVE ROWS;

CREATE INDEX SLR.IDX_FAK_BOP_AMOUNTS_TMP3_01 ON SLR.SLR_FAK_BOP_AMOUNTS_TMP3 (FDB_FAK_ID, FDB_BALANCE_DATE, FDB_ID, LAST_IN_YR);
CREATE INDEX SLR.IDX_FAK_BOP_AMOUNTS_TMP3_02 ON SLR.SLR_FAK_BOP_AMOUNTS_TMP3 (FDB_ID, FDB_PERIOD_MONTH, FDB_PERIOD_QTR, FDB_PERIOD_YEAR, FDB_PERIOD_LTD);
