CREATE GLOBAL TEMPORARY TABLE SLR.SLR_EBA_BOP_AMOUNTS_TMP
(
	EDB_FAK_ID VARCHAR2(32) NOT NULL ENABLE,
	EDB_EBA_ID VARCHAR2(32) NOT NULL ENABLE,
	EDB_BALANCE_DATE DATE NOT NULL ENABLE,
	EDB_BALANCE_TYPE NUMBER(3,0) NOT NULL ENABLE,
	EDB_TRAN_BOP_MTD_BALANCE NUMBER(33,3),
	EDB_TRAN_BOP_QTD_BALANCE NUMBER(33,3),
	EDB_TRAN_BOP_YTD_BALANCE NUMBER(33,3),
	EDB_BASE_BOP_MTD_BALANCE NUMBER(33,3),
	EDB_BASE_BOP_QTD_BALANCE NUMBER(33,3),
	EDB_BASE_BOP_YTD_BALANCE NUMBER(33,3),
	EDB_LOCAL_BOP_MTD_BALANCE NUMBER(33,3),
	EDB_LOCAL_BOP_QTD_BALANCE NUMBER(33,3),
	EDB_LOCAL_BOP_YTD_BALANCE NUMBER(33,3),
	EDB_PERIOD_MONTH NUMBER(2,0) NOT NULL ENABLE,
	EDB_PERIOD_QTR NUMBER(1,0) NOT NULL ENABLE,
	EDB_PERIOD_YEAR NUMBER(4,0) NOT NULL ENABLE,
	EDB_PERIOD_LTD NUMBER(2,0) NOT NULL ENABLE,
	EDB_AMENDED_ON DATE NOT NULL ENABLE
) ON COMMIT PRESERVE ROWS;

CREATE INDEX SLR.IDX_EBA_BOP_AMOUNTS_TMP_01 ON SLR.SLR_EBA_BOP_AMOUNTS_TMP (EDB_FAK_ID, EDB_EBA_ID, EDB_BALANCE_DATE);
