CREATE GLOBAL TEMPORARY TABLE SLR.SLR_EBA_BOP_AMOUNTS_TMP2
(
	EDB_FAK_ID VARCHAR2(32) NOT NULL ENABLE,
	EDB_EBA_ID VARCHAR2(32) NOT NULL ENABLE,
	EDB_BALANCE_DATE DATE NOT NULL ENABLE,
	EDB_BALANCE_TYPE NUMBER(2,0) NOT NULL ENABLE,
	EDB_ENTITY VARCHAR2(20 BYTE) NOT NULL ENABLE,
	EDB_EPG_ID VARCHAR2(18 BYTE) NOT NULL ENABLE,
	EDB_ID VARCHAR2(110 BYTE) NOT NULL ENABLE
) ON COMMIT PRESERVE ROWS;

CREATE INDEX SLR.IDX_EBA_BOP_AMOUNTS_TMP2_01 ON SLR.SLR_EBA_BOP_AMOUNTS_TMP2 (EDB_FAK_ID, EDB_EBA_ID, EDB_BALANCE_DATE);
