DECLARE
    i INTEGER;
BEGIN

    SELECT COUNT(*) INTO i FROM user_tables WHERE table_name = 'SLR_FAK_DAILY_BALANCES_TMP';
    IF i = 1 THEN
        EXECUTE IMMEDIATE 'DROP TABLE SLR_FAK_DAILY_BALANCES_TMP';        
    END IF;

    SELECT COUNT(*) INTO i FROM user_tables WHERE table_name = 'SLR_EBA_DAILY_BALANCES_TMP';
    IF i = 1 THEN
        EXECUTE IMMEDIATE 'DROP TABLE SLR_EBA_DAILY_BALANCES_TMP';        
    END IF;

END;
/