DECLARE
  COUNT_INDEXES INTEGER;
BEGIN
  SELECT COUNT(*) INTO COUNT_INDEXES
    FROM USER_INDEXES
    WHERE UPPER(INDEX_NAME) = 'IDX_JL_SOURCE_JRNL_ID';

  IF COUNT_INDEXES > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_JL_SOURCE_JRNL_ID';
  END IF;
 
END;
/
@@../aahCustom/aahSubLedger/src/main/db/indices/slr/slr_jrnl_lines.sql