create table stn.accounting_event
(
    row_sid                   number   ( 38 , 0 )              generated by default as identity not null
,   event_typ                 varchar2 ( 20 char )                                              not null
,   event_typ_descr           varchar2 ( 80 char )                                              not null
,   business_event_typ        varchar2 ( 20 char )                                              not null
,   business_event_typ_descr  varchar2 ( 80 char )                                              not null
,   event_subgrp              varchar2 ( 20 char )                                              not null
,   event_subgrp_descr        varchar2 ( 80 char )                                              not null
,   event_grp                 varchar2 ( 20 char )                                              not null
,   event_grp_descr           varchar2 ( 80 char )                                              not null
,   event_class               varchar2 ( 20 char )                                              not null
,   event_class_descr         varchar2 ( 80 char )                                              not null
,   lpg_id                    number   ( 38 , 0 )  default 1                                    not null
,   event_status              varchar2 ( 1 char )  default 'U'                                  not null
,   feed_uuid                 raw ( 16 )                                                        not null
,   no_retries                number ( 38 , 0 )    default 0                                    not null
,   step_run_sid              number ( 38 , 0 )    default 0                                    not null
,   constraint pk_ae primary key ( row_sid )
,   constraint uk_ae unique      ( event_typ , feed_uuid )
);