ALTER TABLE STN.CEV_IDENTIFIED_RECORD
 DROP PRIMARY KEY CASCADE;

DROP TABLE STN.CEV_IDENTIFIED_RECORD CASCADE CONSTRAINTS;

CREATE TABLE STN.CEV_IDENTIFIED_RECORD
(
  ROW_SID  NUMBER(38)                           NOT NULL
)
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE UNIQUE INDEX STN.PK_CEV_IR ON STN.CEV_IDENTIFIED_RECORD
(ROW_SID);


ALTER TABLE STN.CEV_IDENTIFIED_RECORD ADD (
  CONSTRAINT PK_CEV_IR
  PRIMARY KEY
  (ROW_SID)
  USING INDEX STN.PK_CEV_IR
  ENABLE VALIDATE);

GRANT SELECT ON STN.CEV_IDENTIFIED_RECORD TO AAH_READ_ONLY;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON STN.CEV_IDENTIFIED_RECORD TO AUTOMATED_UNIT_TEST;
