create table stn.db_tab_column
(
    dtc_id    number generated by default as identity not null
,   dbt_id    number                                  not null
,   column_nm varchar2 ( 30 char )                    not null
,   constraint ck_column_nm check ( column_nm = lower ( column_nm ) )
,   constraint pk_dtc primary key ( dtc_id )
,   constraint uk_dtc unique ( dbt_id , column_nm )
);