create table stn.db_table
(
    dbt_id   number                generated by default as identity not null
,   db_nm    varchar2 ( 128 char )                                  not null
,   table_nm varchar2 ( 128 char )                                  not null
,   constraint pk_dbt primary key ( dbt_id )
,   constraint uk_dbt unique      ( db_nm , table_nm )
,   constraint ck_dbt_database_nm check ( db_nm    = trim ( lower ( db_nm ) ) )
,   constraint ck_dbt_table_nm    check ( table_nm = trim ( lower ( table_nm ) ) )
);