create table stn.department
(
    row_sid      number   ( 38 , 0 )  generated by default as identity not null
,   dept_cd      varchar2 ( 20 char )                                  not null
,   effective_dt date                                                  not null
,   dept_sts     varchar2 ( 1 char )                                   not null
,   dept_descr   varchar2 ( 100 char )                                 not null
,   lpg_id       number   ( 38 , 0 ) default 1                         not null
,   event_status varchar2 ( 1 char ) default 'U'                       not null
,   feed_uuid    raw ( 16 )                                            not null
,   no_retries   number ( 38 , 0 )   default 0                         not null
,   step_run_sid number ( 38 , 0 )   default 0                         not null
,   constraint pk_dept     primary key ( row_sid )
,   constraint uk_dept     unique      ( dept_cd , effective_dt , feed_uuid )
,   constraint ck_dept_sts check       ( dept_sts in ( 'A' , 'I' ) )
);