create table stn.gl_account
(
    row_sid      number   ( 38 , 0 )             generated by default as identity not null
,   acct_cd      varchar2 ( 8 char )                                              not null
,   effective_dt date                                                             not null
,   acct_sts     varchar2 ( 1 char )                                              not null
,   acct_typ     varchar2 ( 1 char )                                              not null
,   acct_cat     varchar2 ( 1 char )                                              not null
,   acct_descr   varchar2 ( 100 char )                                            not null
,   lpg_id       number   ( 38 , 0 ) default 1                                    not null
,   event_status varchar2 ( 1 char ) default 'U'                                  not null
,   feed_uuid    raw ( 16 )                                                       not null
,   no_retries   number ( 38 , 0 )   default 0                                    not null
,   step_run_sid number ( 38 , 0 )   default 0                                    not null
,   constraint pk_gla          primary key ( row_sid )
,   constraint uk_gla          unique      ( acct_cd , effective_dt , feed_uuid )
,   constraint ck_gla_acct_sts check       ( acct_sts in ( 'A' , 'I' ) )
,   constraint ck_gla_acct_typ check       ( acct_typ in ( 'B' , 'P' , 'S' ) )
);