create table stn.gl_combo_edit_rule
(
    row_sid          number   ( 38 , 0 )  generated by default as identity not null
,   prc_cd           varchar2 ( 20 char )                                  not null
,   acct_cd          varchar2 ( 10 char )                                  not null
,   dept_cd          varchar2 ( 20 char )                                      null
,   product_cd       varchar2 ( 20 char )                                      null
,   affiliate_le_cd  varchar2 ( 20 char )                                      null
,   lpg_id           number   ( 38 , 0 )   default 1                       not null
,   event_status     varchar2 ( 1 char )   default 'U'                     not null
,   feed_uuid        raw      ( 16 )                                       not null
,   no_retries       number   ( 38 , 0 )   default 0                       not null
,   step_run_sid     number   ( 38 , 0 )   default 0                       not null
,   constraint pk_cer               primary key ( row_sid )
,   constraint uk_cer               unique      ( prc_cd , acct_cd , feed_uuid )
);