create table stn.gl_combo_edit_process
(
    row_sid          number   ( 38 , 0 )  generated by default as identity not null
,   prc_cd           varchar2 ( 20 char )                                  not null
,   prc_descr        varchar2 ( 100 char )                                 not null
,   prc_typ          varchar2 ( 10 char )                                  not null
,   prc_subject      varchar2 ( 20 char )                                  not null
,   must_match       varchar2 ( 1 char )                                   not null
,   lpg_id           number   ( 38 , 0 )   default 1                       not null
,   event_status     varchar2 ( 1 char )   default 'U'                     not null
,   feed_uuid        raw      ( 16 )                                       not null
,   no_retries       number   ( 38 , 0 )   default 0                       not null
,   step_run_sid     number   ( 38 , 0 )   default 0                       not null
,   constraint pk_gcr               primary key ( row_sid )
,   constraint uk_gcr               unique      ( prc_cd , feed_uuid )
,   constraint ck_prc_typ           check       ( prc_typ       in ('VALID','INVALID') )
,   constraint ck_must_match        check       ( must_match    in ('Y','N')           )
);