create table stn.gl_combo_edit_rule
(
    row_sid          number   ( 38 , 0 )  generated by default as identity not null
,   prc_cd           varchar2 ( 20 char )                                  not null
,   acct_cd          varchar2 ( 8 char )                                   not null
,   prc_rule         varchar2 ( 100 char )                                 not null
,   department       varchar2 ( 100 char )                                     null
,   product      	 varchar2 ( 100 char )                                     null
,   affiliate        varchar2 ( 100 char )                                     null
,   lpg_id           number   ( 38 , 0 )   default 1                       not null
,   event_status     varchar2 ( 1 char )   default 'U'                     not null
,   feed_uuid        raw      ( 16 )                                       not null
,   no_retries       number   ( 38 , 0 )   default 0                       not null
,   step_run_sid     number   ( 38 , 0 )   default 0                       not null
,   constraint pk_cer               primary key ( row_sid )
,   constraint uk_cer               unique      ( prc_cd , acct_cd , feed_uuid )
);