create table stn.gl_chartfield
(
    row_sid          number   ( 38 , 0 )  generated by default as identity not null
,   chartfield_typ   varchar2 ( 20 char )                                  not null
,   chartfield_cd    varchar2 ( 20 char )                                  not null
,   chartfield_descr varchar2 ( 100 char )                                 not null
,   effective_dt     date                                                  not null
,   chartfield_sts   varchar2 ( 1 char )                                   not null
,   lpg_id           number   ( 38 , 0 )   default 1                       not null
,   event_status     varchar2 ( 1 char )   default 'U'                     not null
,   feed_uuid        raw      ( 16 )                                       not null
,   no_retries       number   ( 38 , 0 )   default 0                       not null
,   step_run_sid     number   ( 38 , 0 )   default 0                       not null
,   constraint pk_glc               primary key ( row_sid )
,   constraint uk_glc               unique      ( chartfield_typ , chartfield_cd , effective_dt , feed_uuid )
,   constraint ck_gl_chartfield_sts check       ( chartfield_sts in ( 'A' , 'I' ) )
);