create table stn.legal_entity_alias
(
    row_sid                 number   ( 38 , 0 )             generated by default as identity not null
,   le_id                   number   ( 38 , 0 )                                              not null
,   alias_le_cd             varchar2 ( 20 char )                                             not null
,   alias_le_descr          varchar2 ( 100 char )                                            not null
,   lpg_id                  number   ( 38 , 0 ) default 1                                    not null
,   event_status            varchar2 ( 1 char ) default 'U'                                  not null
,   feed_uuid               raw      ( 16 )                                                  not null
,   no_retries              number   ( 38 , 0 ) default 0                                    not null
,   step_run_sid            number   ( 38 , 0 ) default 0                                    not null
,   constraint pk_lea primary key ( row_sid )
,   constraint uk_lea_cd unique   ( le_id, feed_uuid )
);