create table stn.legal_entity
(
    row_sid                 number   ( 38 , 0 )             generated by default as identity not null
,   le_id                   number   ( 38 , 0 )                                              not null
,   le_cd                   varchar2 ( 20 char )                                             not null
,   le_descr                varchar2 ( 100 char )                                            not null
,   functional_ccy          varchar2 ( 3 char )
,   legal_entity_typ        varchar2 ( 20 char )                                             not null
,   is_ledger_entity        varchar2 ( 1 char ) default 'N'                                  not null
,   is_interco_elim_entity  varchar2 ( 1 char ) default 'N'                                  not null
,   is_vie_consol_entity    varchar2 ( 1 char ) default 'N'                                  not null
,   rpt_cd                  varchar2 ( 20 char )
,   rpt_descr               varchar2 ( 100 char )
,   lpg_id                  number   ( 38 , 0 ) default 1                                    not null
,   event_status            varchar2 ( 1 char ) default 'U'                                  not null
,   feed_uuid               raw ( 16 )                                                       not null
,   no_retries              number ( 38 , 0 )   default 0                                    not null
,   step_run_sid            number ( 38 , 0 )   default 0                                    not null
,   constraint pk_le                     primary key ( row_sid )
,   constraint uk_le_cd                  unique      ( le_cd, feed_uuid )
,   constraint uk_le_id                  unique      ( le_id, feed_uuid )
,   constraint ck_is_ledger_entity       check       ( is_ledger_entity       in ( 'Y' , 'N' ) )
,   constraint ck_is_interco_elim_entity check       ( is_interco_elim_entity in ( 'Y' , 'N' ) )
,   constraint ck_is_vie_consol_entity   check       ( is_vie_consol_entity   in ( 'Y' , 'N' ) )
,   constraint ck_func_ccy_internal      check       (
                                                            ( legal_entity_typ  = 'INTERNAL' and functional_ccy is not null )
                                                         or ( is_ledger_entity  = 'Y'        and functional_ccy is not null )
                                                         or ( legal_entity_typ != 'INTERNAL' and is_ledger_entity = 'N'     )
                                                     )
);