create table stn.posting_financial_calc
(
    fin_calc_id  number ( 38, 0 )     generated by default as identity not null
,   fin_calc_cd  varchar2 ( 20 char )                                  not null
,   constraint pk_fin_calc     primary key ( fin_calc_id )
,   constraint uk_fin_calc     unique      ( fin_calc_cd )
);