create table stn.posting_method_derivation_mtm
(
    event_typ_id      number ( 38 , 0 )                                                 not null
,   is_mark_to_market varchar2 ( 1  char )                                              not null
,   premium_typ       varchar2 ( 1  char )                                              not null
,   psm_id            number ( 38 , 0 )                                                 not null
,   row_sid           number ( 38 , 0 )                generated by default as identity not null
,   constraint pk_psmdm                   primary key ( row_sid )
,   constraint uk_psmdm                   unique      ( event_typ_id , is_mark_to_market , premium_typ )
,   constraint ck_psmdm_is_mark_to_market check       ( is_mark_to_market in ( 'Y' , 'N' ) )
);