create table stn.posting_ledger
(
    ledger_id number ( 38 , 0 )    generated by default as identity not null
,   ledger_cd varchar2 ( 20 char )                                  not null
,   constraint pk_pldgr primary key ( ledger_id )
,   constraint uk_pldgr unique      ( ledger_cd )
);