create table stn.user_detail
(
    row_sid          number   ( 38 , 0 )  generated by default as identity not null
,   employee_id      number   ( 10 , 0 )                                   not null
,   user_nm          varchar2 ( 20 char )                                  not null
,   first_nm         varchar2 ( 40 char )                                  not null
,   last_nm          varchar2 ( 40 char )                                  not null
,   email_address    varchar2 ( 100 char )                                 not null
,   dept_cd          varchar2 ( 20 char )                                  not null
,   lpg_id           number   ( 38 , 0 )   default 1                       not null
,   event_status     varchar2 ( 1 char )   default 'U'                     not null
,   feed_uuid        raw      ( 16 )                                       not null
,   no_retries       number   ( 38 , 0 )   default 0                       not null
,   step_run_sid     number   ( 38 , 0 )   default 0                       not null
,   constraint pk_au       primary key ( row_sid )
,   constraint uk_aunm     unique      ( user_nm , feed_uuid )
,   constraint uk_aeid     unique      ( employee_id , feed_uuid )
,   constraint ck_email    check       ( regexp_like ( email_address , '^(\S+)\@(\S+)\.(\S+)$' ) )
);