create table stn.user_group
(
    row_sid          number   ( 38 , 0 )  generated by default as identity not null
,   user_nm          varchar2 ( 30 char )                                  not null
,   group_nm         varchar2 ( 300 char )                                 not null
,   lpg_id           number   ( 38 , 0 )   default 1                       not null
,   event_status     varchar2 ( 1 char )   default 'U'                     not null
,   feed_uuid        raw      ( 16 )                                       not null
,   no_retries       number   ( 38 , 0 )   default 0                       not null
,   step_run_sid     number   ( 38 , 0 )   default 0                       not null
,   constraint pk_ug                primary key ( row_sid )
,   constraint uk_ug                unique      ( user_nm , group_nm , feed_uuid )
);