create table stn.user
(
    row_sid          number   ( 38 , 0 )  generated by default as identity not null
,   user_nm          varchar2 ( 30 char )                                  not null
,   first_nm         varchar2 ( 40 char )                                  not null
,   last_nm          varchar2 ( 40 char )                                  not null
,   email_address    varchar2 ( 100 char )                                 not null
,   dept_cd          varchar2 ( 20 char )                                  not null
,   lpg_id           number   ( 38 , 0 )   default 1                       not null
,   event_status     varchar2 ( 1 char )   default 'U'                     not null
,   feed_uuid        raw      ( 16 )                                       not null
,   no_retries       number   ( 38 , 0 )   default 0                       not null
,   step_run_sid     number   ( 38 , 0 )   default 0                       not null
,   constraint pk_au                primary key ( row_sid )
,   constraint uk_au                unique      ( user_nm , feed_uuid )
);