create table stn.vie_code
(
    vie_id       number ( 38 , 0 ) generated by default as identity not null
,   vie_cd       number ( 1 )                                       not null
,   vie_cd_descr varchar2 ( 100 )                                   not null
,   sub_event    varchar2 ( 100 char )
,   constraint pk_vie primary key ( vie_id )
,   constraint uk_vie unique      ( vie_cd )
);