CREATE OR REPLACE FORCE VIEW slr.v_slr_jrnl_lines_unposted_jt (
    jlu_jrnl_hdr_id,
    jlu_jrnl_line_number,
    jlu_fak_id,
    jlu_eba_id,
    jlu_jrnl_status,
    jlu_jrnl_status_text,
    jlu_jrnl_process_id,
    jlu_description,
    jlu_source_jrnl_id,
    jlu_effective_date,
    jlu_value_date,
    jlu_entity,
    jlu_epg_id,
    jlu_account,
    jlu_segment_1,
    jlu_segment_2,
    jlu_segment_3,
    jlu_segment_4,
    jlu_segment_5,
    jlu_segment_6,
    jlu_segment_7,
    jlu_segment_8,
    jlu_segment_9,
    jlu_segment_10,
    jlu_attribute_1,
    jlu_attribute_2,
    jlu_attribute_3,
    jlu_attribute_4,
    jlu_attribute_5,
    jlu_reference_1,
    jlu_reference_2,
    jlu_reference_3,
    jlu_reference_4,
    jlu_reference_5,
    jlu_reference_6,
    jlu_reference_7,
    jlu_reference_8,
    jlu_reference_9,
    jlu_reference_10,
    jlu_tran_ccy,
    jlu_tran_amount,
    jlu_base_rate,
    jlu_base_ccy,
    jlu_base_amount,
    jlu_local_rate,
    jlu_local_ccy,
    jlu_local_amount,
    jlu_created_by,
    jlu_created_on,
    jlu_amended_by,
    jlu_amended_on,
    jlu_jrnl_type,
    jlu_jrnl_date,
    jlu_jrnl_description,
    jlu_jrnl_source,
    jlu_jrnl_source_jrnl_id,
    jlu_jrnl_authorised_by,
    jlu_jrnl_authorised_on,
    jlu_jrnl_validated_by,
    jlu_jrnl_validated_on,
    jlu_jrnl_posted_by,
    jlu_jrnl_posted_on,
    jlu_jrnl_total_hash_debit,
    jlu_jrnl_total_hash_credit,
    jlu_jrnl_pref_static_src,
    jlu_jrnl_ref_id,
    jlu_jrnl_rev_date,
    jlu_translation_date,
    jlu_period_month,
    jlu_period_year,
    jlu_period_ltd,
    jlu_jrnl_internal_period_flag,
    jlu_type,
    jt_balance_type,
    jt_balance_type_number,
    jlu_period_qtr
) BEQUEATH DEFINER AS
    SELECT
        slr_jrnl_lines_unposted.jlu_jrnl_hdr_id,
        slr_jrnl_lines_unposted.jlu_jrnl_line_number,
        slr_jrnl_lines_unposted.jlu_fak_id,
        slr_jrnl_lines_unposted.jlu_eba_id,
        slr_jrnl_lines_unposted.jlu_jrnl_status,
        slr_jrnl_lines_unposted.jlu_jrnl_status_text,
        slr_jrnl_lines_unposted.jlu_jrnl_process_id,
        slr_jrnl_lines_unposted.jlu_description,
        slr_jrnl_lines_unposted.jlu_source_jrnl_id,
        slr_jrnl_lines_unposted.jlu_effective_date,
        slr_jrnl_lines_unposted.jlu_value_date,
        slr_jrnl_lines_unposted.jlu_entity,
        slr_jrnl_lines_unposted.jlu_epg_id,
        slr_jrnl_lines_unposted.jlu_account,
        slr_jrnl_lines_unposted.jlu_segment_1,
        slr_jrnl_lines_unposted.jlu_segment_2,
        slr_jrnl_lines_unposted.jlu_segment_3,
        slr_jrnl_lines_unposted.jlu_segment_4,
        slr_jrnl_lines_unposted.jlu_segment_5,
        slr_jrnl_lines_unposted.jlu_segment_6,
        slr_jrnl_lines_unposted.jlu_segment_7,
        slr_jrnl_lines_unposted.jlu_segment_8,
        slr_jrnl_lines_unposted.jlu_segment_9,
        slr_jrnl_lines_unposted.jlu_segment_10,
        slr_jrnl_lines_unposted.jlu_attribute_1,
        slr_jrnl_lines_unposted.jlu_attribute_2,
        slr_jrnl_lines_unposted.jlu_attribute_3,
        slr_jrnl_lines_unposted.jlu_attribute_4,
        slr_jrnl_lines_unposted.jlu_attribute_5,
        slr_jrnl_lines_unposted.jlu_reference_1,
        slr_jrnl_lines_unposted.jlu_reference_2,
        slr_jrnl_lines_unposted.jlu_reference_3,
        slr_jrnl_lines_unposted.jlu_reference_4,
        slr_jrnl_lines_unposted.jlu_reference_5,
        slr_jrnl_lines_unposted.jlu_reference_6,
        slr_jrnl_lines_unposted.jlu_reference_7,
        slr_jrnl_lines_unposted.jlu_reference_8,
        slr_jrnl_lines_unposted.jlu_reference_9,
        slr_jrnl_lines_unposted.jlu_reference_10,
        slr_jrnl_lines_unposted.jlu_tran_ccy,
        slr_jrnl_lines_unposted.jlu_tran_amount,
        coalesce(jlf_base_rate, jlu_base_rate)           AS jlu_base_rate,
        coalesce(jlf_base_ccy, jlu_base_ccy)             AS jlu_base_ccy,
        coalesce(jlf_base_amount, jlu_base_amount)       AS jlu_base_amount,
        coalesce(jlf_local_rate, jlu_local_rate)         AS jlu_local_rate,
        coalesce(jlf_local_ccy, jlu_local_ccy)           AS jlu_local_ccy,
        coalesce(jlf_local_amount, jlu_local_amount)     AS jlu_local_amount,
        slr_jrnl_lines_unposted.jlu_created_by,
        slr_jrnl_lines_unposted.jlu_created_on,
        slr_jrnl_lines_unposted.jlu_amended_by,
        slr_jrnl_lines_unposted.jlu_amended_on,
        slr_jrnl_lines_unposted.jlu_jrnl_type,
        slr_jrnl_lines_unposted.jlu_jrnl_date,
        slr_jrnl_lines_unposted.jlu_jrnl_description,
        slr_jrnl_lines_unposted.jlu_jrnl_source,
        slr_jrnl_lines_unposted.jlu_jrnl_source_jrnl_id,
        slr_jrnl_lines_unposted.jlu_jrnl_authorised_by,
        slr_jrnl_lines_unposted.jlu_jrnl_authorised_on,
        slr_jrnl_lines_unposted.jlu_jrnl_validated_by,
        slr_jrnl_lines_unposted.jlu_jrnl_validated_on,
        slr_jrnl_lines_unposted.jlu_jrnl_posted_by,
        slr_jrnl_lines_unposted.jlu_jrnl_posted_on,
        slr_jrnl_lines_unposted.jlu_jrnl_total_hash_debit,
        slr_jrnl_lines_unposted.jlu_jrnl_total_hash_credit,
        slr_jrnl_lines_unposted.jlu_jrnl_pref_static_src,
        slr_jrnl_lines_unposted.jlu_jrnl_ref_id,
        slr_jrnl_lines_unposted.jlu_jrnl_rev_date,
        slr_jrnl_lines_unposted.jlu_translation_date,
        slr_jrnl_lines_unposted.jlu_period_month,
        slr_jrnl_lines_unposted.jlu_period_year,
        slr_jrnl_lines_unposted.jlu_period_ltd,
        slr_jrnl_lines_unposted.jlu_jrnl_internal_period_flag,
        slr_jrnl_lines_unposted.jlu_type,
        balance_type                                      jt_balance_type,
        balance_type_number                               AS jt_balance_type_number,
        to_number(to_char(SLR_JRNL_LINES_UNPOSTED."JLU_EFFECTIVE_DATE",'Q')) as jlu_period_qtr
    FROM
             slr_jrnl_lines_unposted left
        JOIN slr_jrnl_lines_fx ON jlu_jrnl_hdr_id = jlf_jrnl_hdr_id
                                  AND jlu_jrnl_line_number = jlf_jrnl_line_number
                                  AND jlu_epg_id = jlf_epg_id
        JOIN (
            SELECT
                ejt_type,
                ejt_balance_type_1  AS balance_type,
                1                   AS balance_type_number
            FROM
                slr_ext_jrnl_types
            WHERE
                ejt_balance_type_1 IS NOT NULL
            UNION ALL
            SELECT
                ejt_type,
                ejt_balance_type_2  AS balance_type,
                2                   AS balance_type_number
            FROM
                slr_ext_jrnl_types
            WHERE
                ejt_balance_type_2 IS NOT NULL
        ) bt ON bt.ejt_type = slr_jrnl_lines_unposted.jlu_jrnl_type;