CREATE OR REPLACE VIEW STN.HOPPER_JOURNAL_LINE
(
   LE_ID,
   ACCT_CD,
   LEDGER_CD,
   BASIS_CD,
   BOOK_CD,
   AFFILIATE_LE_ID,
   ACCIDENT_YR,
   UNDERWRITING_YR,
   POLICY_ID,
   STREAM_ID,
   TAX_JURISDICTION_CD,
   POSTING_SCHEMA,
   COUNTERPARTY_LE_ID,
   DEPT_CD,
   CHARTFIELD_1,
   EXECUTION_TYP,
   BUSINESS_TYP,
   OWNER_LE_ID,
   PREMIUM_TYP,
   TRANSACTION_CCY,
   TRANSACTION_AMT,
   SRA_AE_DR_CR,
   ACCOUNTING_DT,
   ULTIMATE_PARENT_LE_ID,
   EVENT_TYP,
   FUNCTIONAL_CCY,
   FUNCTIONAL_AMT,
   REPORTING_CCY,
   REPORTING_AMT,
   SRA_AE_SOURCE_SYSTEM,
   SRA_AE_ITSC_INST_TYP_SCLSS_CD,
   EVENT_STATUS,
   SRA_SI_ACCOUNT_SYS_INST_CODE,
   SRA_SI_INSTR_SYS_INST_CODE,
   SRA_SI_PARTY_SYS_INST_CODE,
   SRA_SI_STATIC_SYS_INST_CODE,
   SRA_AE_PBU_EXT_PARTY_CODE,
   SRA_AE_IPE_INT_ENTITY_CODE,
   SRA_AE_AET_ACC_EVENT_TYPE_CODE,
   SRA_AE_CU_LOCAL_CURRENCY_CODE,
   SRA_AE_CU_BASE_CURRENCY_CODE,
   SRA_AE_I_INSTRUMENT_CLICODE,   
   SRA_AE_IT_INSTR_TYPE_CODE,
   SRA_AE_ITC_INST_TYP_CLS_CODE,
   SRA_AE_PE_PERSON_CODE,       
   SRA_AE_GL_INSTRUMENT_ID,   
   PROCESS_ID,
   MESSAGE_ID,
   LPG_ID,
   SRA_AE_POSTING_DATE,
   SRA_AE_INSTR_TYPE_MAP_CODE
)
AS
   SELECT fsra.sra_ae_pbu_int_entity_code le_id,
          fsra.sra_ae_gl_account_code acct_cd,
          fsra.sra_ae_posting_schema ledger_cd,
          fsra.sra_ae_gaap basis_cd,
          fsra.sra_ae_bo_book_clicode book_cd,
          fsra.sra_ae_dimension_4 affiliate_le_id,
          fsra.sra_ae_dimension_5 accident_yr,
          fsra.sra_ae_dimension_6 underwriting_yr,
          fsra.sra_ae_dimension_7 policy_id,
          fsra.sra_ae_dimension_8 stream_id,
          fsra.sra_ae_dimension_9 tax_jurisdiction_cd,
          fsra.sra_ae_dimension_10 posting_schema,
          fsra.sra_ae_dimension_3 counterparty_le_id,
          fsra.sra_ae_dimension_2 dept_cd,
          fsra.sra_ae_dimension_1 chartfield_1,
          fsra.sra_ae_dimension_11 execution_typ,
          fsra.sra_ae_dimension_12 business_typ,
          fsra.sra_ae_dimension_13 owner_le_id,
          fsra.sra_ae_dimension_14 premium_typ,
          fsra.sra_ae_cu_currency_code transaction_ccy,
          fsra.sra_ae_amount transaction_amt,
          fsra.sra_ae_dr_cr sra_ae_dr_cr,
          fsra.sra_accevent_date accounting_dt,
          fsra.sra_ae_client_spare_id3 ultimate_parent_le_id,
          fsra.sra_ae_client_spare_id4 event_typ,
          fsra.sra_ae_client_spare_id5 functional_ccy,
          fsra.sra_ae_client_spare_id6 functional_amt,
          fsra.sra_ae_client_spare_id7 reporting_ccy,
          fsra.sra_ae_client_spare_id8 reporting_amt,
          fsra.sra_ae_source_system sra_ae_source_system,
          fsra.sra_ae_itsc_inst_typ_sclss_cd sra_ae_itsc_inst_typ_sclss_cd,
          fsra.event_status,
          fsra.sra_si_account_sys_inst_code,
          fsra.sra_si_instr_sys_inst_code,
          fsra.sra_si_party_sys_inst_code,
          fsra.sra_si_static_sys_inst_code,
          fsra.sra_ae_pbu_ext_party_code,
          fsra.sra_ae_ipe_int_entity_code,
          fsra.SRA_AE_AET_ACC_EVENT_TYPE_CODE,
          fsra.SRA_AE_CU_LOCAL_CURRENCY_CODE,
          fsra.SRA_AE_CU_BASE_CURRENCY_CODE,
          fsra.SRA_AE_I_INSTRUMENT_CLICODE,   
          fsra.SRA_AE_IT_INSTR_TYPE_CODE,
          fsra.SRA_AE_ITC_INST_TYP_CLS_CODE,
          fsra.SRA_AE_PE_PERSON_CODE,       
          fsra.SRA_AE_GL_INSTRUMENT_ID,
          fsra.process_id,
          fsra.message_id,
          fsra.lpg_id,
          fsra.sra_ae_posting_date,
          fsra.sra_ae_instr_type_map_code
     FROM fdr.fr_stan_raw_adjustment fsra



