select
  gp_si_sys_inst_id
,  gp_one_id
,  gp_tomorrows_bus_date
,  gp_pe_superuser_id
,  gp_yesterday_bus_date
,  gp_todays_bus_date
,  gp_software_version
,  gp_la_sys_message_lang_id
,  gp_si_onite_mtm_system_id
,  gp_fx_rate_daily_var_alarm
,  gp_max_adj_days_back
,  gp_rec_db_link
,  gp_last_month_end_date
,  gp_environment_name
,  gp_environment_desc
,  gp_this_month_start_date
,  gp_this_month_end_date
,  gp_settle_tolerance_amount
,  gp_client_date_1
,  gp_max_retries
,  gp_build_number
,  gp_last_month_end_bus_date
,  gp_this_month_start_bus_date
,  gp_this_month_end_bus_date
,  gp_default_acc_flag
,  gp_prevs_months_end_bus_date
,  gp_processing_status
,  gp_lpg_name
,  gp_lpg_desc
,  lpg_id
,  gp_check_back_dated_in_ae
,  gp_ca_processing_cal_name
from er_fr_global_parameter