select
       ae_client_spare_id14
     , ae_client_spare_id12
     , ae_gl_account
     , ae_aet_acc_event_type_id
     , ae_in_repository_ind
     , ae_posting_date
     , ae_accevent_date
     , ae_amount
     , ae_iso_currency_code
     , ae_ledger_period
     , ae_local_amount
     , ae_gl_account_alias
     , ae_local_currency_code
     , ae_gl_entity
     , ae_epg_id
     , ae_gl_book
     , ae_gl_profit_centre
     , ae_gl_instr_super_class
     , ae_ledger_rec_status
     , ae_value_date
     , ae_gl_instrument_id
     , ae_gl_party_business_id
     , ae_gl_person_id
     , ae_client_spare_id1
     , ae_client_spare_id2
     , ae_client_spare_id3
     , ae_client_spare_id4
     , ae_client_spare_id5
     , ae_client_spare_id6
     , ae_client_spare_id7
     , ae_client_spare_id8
     , ae_client_spare_id9
     , ae_client_spare_id10
     , ae_source_tran_no
     , ae_gl_narrative
     , ae_ledger_rec_status2
     , ae_gl_transaction_id
     , ae_rep_schema_upd
     , ae_transaction_no
     , ae_rule_id
     , ae_rules_amount_ref_id
     , ae_sub_ledger_upd
     , ae_i_instrument_id
     , ae_fdr_tran_no
     , ae_client_spare_id11
     , ae_il_instr_leg_id
     , ae_source_system
     , ae_journal_type
     , ae_gl_ledger_id
     , ae_base_currency_code
     , lpg_id
--     , ae_source_jrnl_id
     , ae_sub_event_id
     , ae_posting_schema
     , ae_gaap
     , ae_posting_code
     , ae_reverse_date
     , ae_dr_cr
     , ae_base_rate
     , ae_local_rate
     , ae_rate_date
     , ae_dimension_1
     , ae_dimension_2
     , ae_dimension_3
     , ae_dimension_4
     , ae_dimension_5
     , ae_dimension_6
     , ae_dimension_7
     , ae_dimension_8
     , ae_dimension_9
     , ae_dimension_10
     , ae_dimension_11
     , ae_dimension_12
     , ae_dimension_13
     , ae_dimension_14
     , ae_dimension_15
     , ae_gl_cost_centre
     , ae_ret_amort_flag
     , ae_gl_client1_org_unit_id
     , ae_gl_client2_org_unit_id
     , ae_gl_client3_org_unit_id
     , ae_gl_plant_id
     , ae_gl_ship_to_country_id
     , ae_gl_product_part_id
     , ae_client_date1
     , ae_gl_cash_flow_type
     , ae_gl_tax_code_id
     , ae_gl_contract_id
     , ae_gl_rights_categ_id
     , ae_gl_rights_subcateg_id
     , ae_translation_date
     , ae_ret_recog_type_id
     , ae_base_amount
     , ae_number_of_periods
     , ae_calc_period
     , ae_ret_agv_or_arrears
     , ae_ret_ca_calendar_name
     , ae_ret_post_period
     , ae_client_spare_id13
     , ae_client_spare_id15
     , ae_client_spare_id16
     , ae_client_spare_id17
     , ae_client_spare_id18
     , ae_client_spare_id19
     , ae_client_spare_id20
     , ae_client_date2
     , ae_client_date3
     , ae_client_date4
     , ae_client_date5
  from
       er_fr_accounting_event_imp