CREATE TABLE rdr.rr_glint_to_slr_ag
(

  RGJL_ID              NUMBER(18)               NOT NULL,
  JL_JRNL_HDR_ID       CHAR(32 BYTE)            NOT NULL,
  JL_JRNL_LINE_NUMBER  NUMBER(12)               NOT NULL
);

COMMENT ON TABLE RDR.RR_GLINT_TO_SLR_AG IS 'MAPS SLR JOURNALS TO GLINT JOURNALS';