CREATE GLOBAL TEMPORARY TABLE "RDR"."RR_GLINT_TEMP_JOURNAL" 
   (	"JH_JRNL_ID" NUMBER(18,0) NOT NULL ENABLE, 
	"JH_JRNL_DATE" DATE, 
	"JH_JRNL_ENTITY" VARCHAR2(30 BYTE), 
	"JH_JRNL_EPG_ID" VARCHAR2(18 BYTE),
    "JH_JRNL_TYPE" VARCHAR2(40 BYTE),
    "JH_JRNL_INTERNAL_PERIOD_FLAG" CHAR(1 BYTE),
    "JH_JRNL_DESCRIPTION" VARCHAR2(100 BYTE),
	"PREVIOUS_FLAG" CHAR(1 BYTE), 
	"LKT_LOOKUP_TYPE_CODE" VARCHAR2(100 BYTE), 
	 CONSTRAINT "XPKRR_GLINT_TEMP_JOURNAL" PRIMARY KEY ("JH_JRNL_ID") ENABLE
   ) ON COMMIT DELETE ROWS ;

   COMMENT ON COLUMN "RDR"."RR_GLINT_TEMP_JOURNAL"."JH_JRNL_ID" IS 'The AAH Journal Internal Identifier (SLR_JRNL_HEADERS).';
   COMMENT ON COLUMN "RDR"."RR_GLINT_TEMP_JOURNAL"."JH_JRNL_DATE" IS 'The Journal Date.';
   COMMENT ON COLUMN "RDR"."RR_GLINT_TEMP_JOURNAL"."JH_JRNL_ENTITY" IS 'The Entity of the Journal.';
   COMMENT ON COLUMN "RDR"."RR_GLINT_TEMP_JOURNAL"."JH_JRNL_EPG_ID" IS 'The Entity Processing Group Identifier.';
   COMMENT ON COLUMN "RDR"."RR_GLINT_TEMP_JOURNAL"."PREVIOUS_FLAG" IS 'Whether the Journal has previously been sent to the GL (Y) or not (N).';
   COMMENT ON COLUMN "RDR"."RR_GLINT_TEMP_JOURNAL"."LKT_LOOKUP_TYPE_CODE" IS 'The GLINT configuration type code for the journal.';
   COMMENT ON TABLE "RDR"."RR_GLINT_TEMP_JOURNAL"  IS 'Temporary table to hold the journals that will be sent to the GL for a particular interface run.';