CREATE TABLE rdr.rr_glint_journal_line 
(
  RGJL_ID                NUMBER(18)             NOT NULL,
  RGJL_RGJ_ID            VARCHAR2(30 BYTE)      NOT NULL,
  RGJL_RGJ_RGBC_ID       NUMBER(18)             NOT NULL,
  RGJL_AAH_JOURNAL       NUMBER(18),
  RGJL_AAH_JOURNAL_LINE  NUMBER(18),
  INPUT_TIME             DATE                   DEFAULT SYSDATE               NOT NULL,
  INPUT_USER             VARCHAR2(30 BYTE)      DEFAULT USER                  NOT NULL,
  MODIFIED_TIME          DATE                   DEFAULT SYSDATE               NOT NULL,
  MODIFIED_USER          VARCHAR2(30 BYTE)      DEFAULT USER                  NOT NULL,
  GL_DISTRIB_STATUS      CHAR(1 BYTE)           NOT NULL,
  APPL_JRNL_ID           VARCHAR2(10 BYTE)      NOT NULL,
  BUSINESS_UNIT_GL       VARCHAR2(5 BYTE)       NOT NULL,
  BUSINESS_UNIT          VARCHAR2(5 BYTE)       NOT NULL,
  LEDGER_GROUP           VARCHAR2(10 BYTE)      NOT NULL,
  LEDGER                 VARCHAR2(10 BYTE)      NOT NULL,
  JOURNAL_ID             VARCHAR2(10 BYTE)      NOT NULL,
  JOURNAL_DATE           DATE,
  JOURNAL_LINE           NUMBER(9)              NOT NULL,
  ACCOUNTING_DT          DATE,
  FISCAL_YEAR            NUMBER(4)              NOT NULL,
  ACCOUNTING_PERIOD      NUMBER(3)              NOT NULL,
  FOREIGN_CURRENCY       VARCHAR2(3 BYTE)       NOT NULL,
  FOREIGN_AMOUNT         NUMBER(23,3)           NOT NULL,
  CURRENCY_CD            VARCHAR2(3 BYTE)       NOT NULL,
  MONETARY_AMOUNT        NUMBER(23,3)           NOT NULL,
  ACCOUNT                VARCHAR2(10 BYTE)      NOT NULL,
  DEPTID                 VARCHAR2(10 BYTE)      NOT NULL,
  PRODUCT                VARCHAR2(6 BYTE)       NOT NULL,
  AFFILIATE              VARCHAR2(5 BYTE)       NOT NULL,
  PROGRAM_CODE           VARCHAR2(5 BYTE)       NOT NULL,
  CHARTFIELD1            VARCHAR2(10 BYTE)      NOT NULL,
  LINE_DESCR             VARCHAR2(30 BYTE)      NOT NULL,
  JRNL_LN_REF            VARCHAR2(10 BYTE)      NOT NULL,
  PROCESS_INSTANCE       NUMBER(10)             NOT NULL,
  NOTES_254              VARCHAR2(256 BYTE)     NOT NULL,
  DTTM_STAMP             DATE,
  EVENT_CLASS            VARCHAR2(30 BYTE)      NOT NULL,
  AAH_JRNL_HDR_NBR       CHAR(32 BYTE)          NOT NULL,
  CREDIT_AMT             NUMBER(23,3),
  DEBIT_AMT              NUMBER(23,3),
  EVENT_STATUS           CHAR(1 BYTE)           NOT NULL,
  SLR_PROCESS_ID         NUMBER(30)             NOT NULL,
  MANUAL_JE              CHAR(1 BYTE)           NOT NULL,
  PS_FILTER              CHAR(1 BYTE)           NOT NULL,
  JH_JRNL_TYPE           VARCHAR2(40 BYTE)      NOT NULL,
  JH_JRNL_DESCRIPTION    VARCHAR2(100 BYTE)     NOT NULL,
     CONSTRAINT "XPK_GLINT_JOURNAL_LINE" PRIMARY KEY ("RGJL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RDR_DATA"  ENABLE, 
     CONSTRAINT "GLINT_J_JL" FOREIGN KEY ("RGJL_RGJ_RGBC_ID", "RGJL_RGJ_ID")
      REFERENCES "RDR"."RR_GLINT_JOURNAL" ("RGJ_RGBC_ID", "RGJ_ID") ENABLE
);

COMMENT ON TABLE RDR.RR_GLINT_JOURNAL_LINE IS 'Stores each of the journal lines that is to be sent to the GL.
Amend the custom columns within this table (and RR_GLINT_TEMP_JOURNAL_LINE) according to the specific General Ledger that is used. The default custom column list is for an Oracle GL.';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.RGJL_ID IS 'The unique identifier for the journal line.
Core Column.';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.RGJL_RGJ_ID IS 'The Journal Identifier as it will appear in the GL (RR_GLINT_JOURNAL).
Core Column.';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.RGJL_RGJ_RGBC_ID IS 'The unique batch identifier (RR_GLINT_BATCH_CONTROL).
Core Column.';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.RGJL_AAH_JOURNAL IS 'If this line has been directly mapped from a SLR Journal Line, then this will be populated with the SLR Journal Identifier.
Core Column.';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.RGJL_AAH_JOURNAL_LINE IS 'If this line has been directly mapped from a SLR Journal Line, then this will be populated with the SLR Journal Line Number.
Core Column.';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.INPUT_TIME IS 'Date/Time the record was first inserted.
Core Column.';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.INPUT_USER IS 'User/Process that created the record.
Core Column.';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.MODIFIED_TIME IS 'Date/Time the record was last updated.
Core Column.';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.MODIFIED_USER IS 'User/Process that last updated the record.
Core Column.';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.GL_DISTRIB_STATUS IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.APPL_JRNL_ID IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.BUSINESS_UNIT_GL IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.BUSINESS_UNIT IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.LEDGER_GROUP IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.LEDGER IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.JOURNAL_ID IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.JOURNAL_DATE IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.JOURNAL_LINE IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.ACCOUNTING_DT IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.FISCAL_YEAR IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.ACCOUNTING_PERIOD IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.FOREIGN_CURRENCY IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.FOREIGN_AMOUNT IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.CURRENCY_CD IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.MONETARY_AMOUNT IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.ACCOUNT IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.DEPTID IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.PRODUCT IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.AFFILIATE IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.PROGRAM_CODE IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.CHARTFIELD1 IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.LINE_DESCR IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.JRNL_LN_REF IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.PROCESS_INSTANCE IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.NOTES_254 IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.DTTM_STAMP IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.EVENT_CLASS IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.AAH_JRNL_HDR_NBR IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.CREDIT_AMT IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.DEBIT_AMT IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.EVENT_STATUS IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.MANUAL_JE IS 'Custom Column';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.PS_FILTER IS 'Custom Column to restrict data in link';

COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.JH_JRNL_TYPE IS 'Custom Column';
  
COMMENT ON COLUMN RDR.RR_GLINT_JOURNAL_LINE.JH_JRNL_DESCRIPTION IS 'Custom Column';