create or replace view rdr.rcv_glint_journal_line (jl_jrnl_hdr_id, jl_jrnl_line_number, jl_fak_id, jl_eba_id, jl_jrnl_status, jl_jrnl_status_text, jl_jrnl_process_id, jl_description, jl_source_jrnl_id, jl_effective_date, jl_value_date, jl_entity, jl_epg_id, jl_account, jl_sub_account, jl_segment_1, jl_segment_2, jl_segment_3, jl_segment_4, jl_segment_5, jl_segment_6, jl_segment_7, jl_segment_8, jl_segment_9, jl_segment_10, jl_attribute_1, jl_attribute_2, jl_attribute_3, jl_attribute_4, jl_attribute_5, jl_reference_1, jl_reference_2, jl_reference_3, jl_reference_4, jl_reference_5, jl_reference_6, jl_reference_7, jl_reference_8, jl_reference_9, jl_reference_10, jl_tran_ccy, jl_tran_amount, jl_base_rate, jl_base_ccy, jl_base_amount, jl_local_rate, jl_local_ccy, jl_local_amount, jl_created_by, jl_created_on, jl_amended_by, jl_amended_on, jl_recon_status, event_group) AS 
  Select jl_jrnl_hdr_id,
       jl_jrnl_line_number,
       jl_fak_id,
       jl_eba_id,
       jl_jrnl_status,
       jl_jrnl_status_text,
       jl_jrnl_process_id,
       jl_description,
       jl_source_jrnl_id,
       jl_effective_date,
       jl_value_date,
       jl_entity,
       jl_epg_id,
       gl.ga_client_text4 as jl_account,
       jl_account as jl_sub_account,      
       jl_segment_1,
       jl_segment_2,
       jl_segment_3,
       jl_segment_4,
       jl_segment_5,
       jl_segment_6,
       jl_segment_7,
       jl_segment_8,
       jl_segment_9,
       jl_segment_10,
       jl_attribute_1,
       jl_attribute_2,
       jl_attribute_3,
       jl_attribute_4,
       jl_attribute_5,
       jl_reference_1,
       jl_reference_2,
       jl_reference_3,
       jl_reference_4,
       jl_reference_5,
       jl_reference_6,
       jl_reference_7,
       jl_reference_8,
       jl_reference_9,
       jl_reference_10,
       jl_tran_ccy,
       jl_tran_amount,
       jl_base_rate,
       jl_base_ccy,
       jl_base_amount,
       jl_local_rate,
       jl_local_ccy,
       jl_local_amount,
       jl_created_by,
       jl_created_on,
       jl_amended_by,
       jl_amended_on,
       jl_recon_status,
       fgl.lk_lookup_value6 as event_group
  from slr.slr_jrnl_lines jl
  left join fdr.fr_general_lookup fgl on jl.jl_attribute_4 = fgl.lk_match_key1
                                      and FGL.LK_LKT_LOOKUP_TYPE_CODE = 'ACCOUNTING_EVENT'
  left join fdr.fr_gl_account gl on jl.jl_account = gl.ga_account_code                                      
 where 1=1;
 comment on table rdr.rcv_glint_journal_line  IS 'Configurable View on Journal Lines that should be considered for sending to the GL.';