create or replace view rdr.rcv_glint_journal_line (jl_jrnl_hdr_id, jl_jrnl_line_number, jl_fak_id, jl_eba_id, jl_jrnl_status, jl_jrnl_status_text, jl_jrnl_process_id, jl_description, jl_source_jrnl_id, jl_effective_date, jl_value_date, jl_entity, jl_epg_id, jl_account, jl_sub_account, jl_segment_1, jl_segment_2, jl_segment_3, jl_segment_4, jl_segment_5, jl_segment_6, jl_segment_7, jl_segment_8, jl_segment_9, jl_segment_10, jl_attribute_1, jl_attribute_2, jl_attribute_3, jl_attribute_4, jl_attribute_5, jl_reference_1, jl_reference_2, jl_reference_3, jl_reference_4, jl_reference_5, jl_reference_6, jl_reference_7, jl_reference_8, jl_reference_9, jl_reference_10, jl_tran_ccy, jl_tran_amount, jl_base_rate, jl_base_ccy, jl_base_amount, jl_local_rate, jl_local_ccy, jl_local_amount, jl_created_by, jl_created_on, jl_amended_by, jl_amended_on, jl_recon_status, event_group, credit_amt, debit_amt, event_status) AS 
 select jl_jrnl_hdr_id,
          cast(jl_jrnl_line_number as number(5,0)) as jl_jrnl_line_number,
          jl_fak_id,
          jl_eba_id,
          jl_jrnl_status,
          jl_jrnl_status_text,
          cast(jl_jrnl_process_id as number(8,0)) as jl_jrnl_process_id,
          cast(nvl(jl_description,' ') as varchar2(30)) as jl_description,
          cast(jl_source_jrnl_id as varchar2(10)) as jl_source_jrnl_id,
          jl_effective_date,
          jl_value_date,
          cast(jl_entity as varchar2(5)) as jl_entity,
          jl_epg_id,
          cast(gl.ga_client_text4 as varchar2(10)) as jl_account,
          jl_account as jl_sub_account,
          cast(case when jl_segment_1 = 'NVS' then ' ' else jl_segment_1 end as varchar2(10)) as jl_segment_1,
          case when jl_segment_2 = 'NVS' then ' ' else jl_segment_2 end as jl_segment_2,
          cast(case when jl_segment_3 = 'NVS' then ' ' else jl_segment_3 end as varchar2(10)) as jl_segment_3,
          cast(case when jl_segment_4 = 'NVS' then ' ' else jl_segment_4 end as varchar2(5)) as jl_segment_4,
          cast(case when jl_segment_5 = 'NVS' then ' ' else jl_segment_5 end as varchar2(6)) as jl_segment_5,
          cast(case when jl_segment_6 = 'NVS' then ' ' else jl_segment_6 end as varchar2(5)) as jl_segment_6,
          case when jl_segment_7 = 'NVS' then ' ' else jl_segment_7 end as jl_segment_7,
          case when jl_segment_8 = 'NVS' then ' ' else jl_segment_8 end as jl_segment_8,
          case when jl_segment_9 = 'NVS' then ' ' else jl_segment_9 end as jl_segment_9,
          case when jl_segment_10 = 'NVS' then ' ' else jl_segment_10 end as jl_segment_10,
          case when jl_attribute_1 = 'NVS' then ' ' else jl_attribute_1 end as jl_attribute_1,
          case when jl_attribute_2 = 'NVS' then ' ' else jl_attribute_2 end as jl_attribute_2,
          case when jl_attribute_3 = 'NVS' then ' ' else jl_attribute_3 end as jl_attribute_3,
          case when jl_attribute_4 = 'NVS' then ' ' else jl_attribute_4 end as jl_attribute_4,
          case when jl_attribute_5 = 'NVS' then ' ' else jl_attribute_5 end as jl_attribute_5,
          case when jl_reference_1 = 'NVS' then ' ' else jl_reference_1 end as jl_reference_1,
          case when jl_reference_2 = 'NVS' then ' ' else jl_reference_2 end as jl_reference_2,
          case when jl_reference_3 = 'NVS' then ' ' else jl_reference_3 end as jl_reference_3,
          case when jl_reference_4 = 'NVS' then ' ' else jl_reference_4 end as jl_reference_4,
          case when jl_reference_5 = 'NVS' then ' ' else jl_reference_5 end as jl_reference_5,
          case when jl_reference_6 = 'NVS' then ' ' else jl_reference_6 end as jl_reference_6,
          case when jl_reference_7 = 'NVS' then ' ' else jl_reference_7 end as jl_reference_7,
          case when jl_reference_8 = 'NVS' then ' ' else jl_reference_8 end as jl_reference_8,
          case when jl_reference_9 = 'NVS' then ' ' else jl_reference_9 end as jl_reference_9,
          case when jl_reference_10 = 'NVS' then ' ' else jl_reference_10 end as jl_reference_10,
          cast(jl_tran_ccy as varchar2(3)) as jl_tran_ccy,
          cast(jl_tran_amount as number(23,3)) as jl_tran_amount,
          jl_base_rate,
          cast(jl_base_ccy as varchar2(3)) as jl_base_ccy,
          cast(jl_base_amount as number(23,3)) as jl_base_amount,
          jl_local_rate,
          jl_local_ccy,
          jl_local_amount,
          jl_created_by,
          jl_created_on,
          jl_amended_by,
          jl_amended_on,
          jl_recon_status,
          nvl(fgl.lk_lookup_value2,' ') as event_group,
          case when jl_tran_amount < 0 then jl_tran_amount else null end as credit_amt,
          case when jl_tran_amount >= 0 then jl_tran_amount else null end as debit_amt,
          'U' as event_status
     from slr.slr_jrnl_lines jl
          left join fdr.fr_general_lookup fgl
             on     jl.jl_attribute_4 = fgl.lk_match_key1
                and fgl.lk_lkt_lookup_type_code = 'EVENT_HIERARCHY'
          left join fdr.fr_gl_account gl
             on jl.jl_account = gl.ga_account_code
    where 1 = 1;
 comment on table rdr.rcv_glint_journal_line  IS 'Configurable View on Journal Lines that should be considered for sending to the GL.';