create or replace force view rdr.rrv_ag_glint_ps_journals
(
   RGJL_ID,
   RGJL_RGJ_ID,
   RGJL_RGJ_RGBC_ID,
   RGJL_AAH_JOURNAL,
   RGJL_AAH_JOURNAL_LINE,
   INPUT_TIME,
   INPUT_USER,
   MODIFIED_TIME,
   MODIFIED_USER,
   GL_DISTRIB_STATUS,
   APPL_JRNL_ID,
   BUSINESS_UNIT_GL,
   BUSINESS_UNIT,
   LEDGER_GROUP,
   LEDGER,
   JOURNAL_ID,
   JOURNAL_DATE,
   JOURNAL_LINE,
   ACCOUNTING_DT,
   FISCAL_YEAR,
   ACCOUNTING_PERIOD,
   FOREIGN_CURRENCY,
   FOREIGN_AMOUNT,
   CURRENCY_CD,
   MONETARY_AMOUNT,
   ACCOUNT,
   DEPTID,
   PRODUCT,
   AFFILIATE,
   PROGRAM_CODE,
   CHARTFIELD1,
   LINE_DESCR,
   JRNL_LN_REF,
   PROCESS_INSTANCE,
   NOTES_254,
   DTTM_STAMP,
   EVENT_CLASS,
   AAH_JRNL_HDR_NBR,
   CREDIT_AMT,
   DEBIT_AMT,
   EVENT_STATUS,
   SLR_PROCESS_ID,
   MANUAL_JE,
   PS_FILTER,
   JL_JRNL_HDR_ID,
   JL_JRNL_LINE_NUMBER,
   JL_FAK_ID,
   JL_EBA_ID,
   JL_JRNL_STATUS,
   JL_JRNL_STATUS_TEXT,
   JL_JRNL_PROCESS_ID,
   JL_DESCRIPTION,
   JL_SOURCE_JRNL_ID,
   JL_EFFECTIVE_DATE,
   JL_VALUE_DATE,
   JL_ENTITY,
   JL_EPG_ID,
   JL_ACCOUNT,
   JL_SEGMENT_1,
   JL_SEGMENT_2,
   JL_SEGMENT_3,
   JL_SEGMENT_4,
   JL_SEGMENT_5,
   JL_SEGMENT_6,
   JL_SEGMENT_7,
   JL_SEGMENT_8,
   JL_SEGMENT_9,
   JL_SEGMENT_10,
   JL_ATTRIBUTE_1,
   JL_ATTRIBUTE_2,
   JL_ATTRIBUTE_3,
   JL_ATTRIBUTE_4,
   JL_ATTRIBUTE_5,
   JL_REFERENCE_1,
   JL_REFERENCE_2,
   JL_REFERENCE_3,
   JL_REFERENCE_4,
   JL_REFERENCE_5,
   JL_REFERENCE_6,
   JL_REFERENCE_7,
   JL_REFERENCE_8,
   JL_REFERENCE_9,
   JL_REFERENCE_10,
   JL_TRAN_CCY,
   JL_TRAN_AMOUNT,
   JL_BASE_RATE,
   JL_BASE_CCY,
   JL_BASE_AMOUNT,
   JL_LOCAL_RATE,
   JL_LOCAL_CCY,
   JL_LOCAL_AMOUNT,
   JL_CREATED_BY,
   JL_CREATED_ON,
   JL_AMENDED_BY,
   JL_AMENDED_ON,
   JL_RECON_STATUS,
   JL_TRANSLATION_DATE,
   JL_BUS_POSTING_DATE,
   JL_PERIOD_MONTH,
   JL_PERIOD_YEAR,
   JL_PERIOD_LTD,
   JL_TYPE
)
AS
   SELECT gjl.rgjl_id,
          gjl.rgjl_rgj_id,
          gjl.rgjl_rgj_rgbc_id,
          gjl.rgjl_aah_journal,
          gjl.rgjl_aah_journal_line,
          gjl.input_time,
          gjl.input_user,
          gjl.modified_time,
          gjl.modified_user,
          gjl.gl_distrib_status,
          gjl.appl_jrnl_id,
          gjl.business_unit_gl,
          gjl.business_unit,
          gjl.ledger_group,
          gjl.ledger,
          gjl.journal_id,
          gjl.journal_date,
          gjl.journal_line,
          gjl.accounting_dt,
          gjl.fiscal_year,
          gjl.accounting_period,
          gjl.foreign_currency,
          gjl.foreign_amount,
          gjl.currency_cd,
          gjl.monetary_amount,
          gjl.account,
          gjl.deptid,
          gjl.product,
          gjl.affiliate,
          gjl.program_code,
          gjl.chartfield1,
          gjl.line_descr,
          gjl.jrnl_ln_ref,
          gjl.process_instance,
          gjl.notes_254,
          gjl.dttm_stamp,
          gjl.event_class,
          gjl.aah_jrnl_hdr_nbr,
          gjl.credit_amt,
          gjl.debit_amt,
          gjl.event_status,
          gjl.slr_process_id,
          gjl.manual_je,
          gjl.ps_filter,
          sjl.jl_jrnl_hdr_id,
          sjl.jl_jrnl_line_number,
          sjl.jl_fak_id,
          sjl.jl_eba_id,
          sjl.jl_jrnl_status,
          sjl.jl_jrnl_status_text,
          sjl.jl_jrnl_process_id,
          sjl.jl_description,
          sjl.jl_source_jrnl_id,
          sjl.jl_effective_date,
          sjl.jl_value_date,
          sjl.jl_entity,
          sjl.jl_epg_id,
          sjl.jl_account,
          sjl.jl_segment_1,
          sjl.jl_segment_2,
          sjl.jl_segment_3,
          sjl.jl_segment_4,
          sjl.jl_segment_5,
          sjl.jl_segment_6,
          sjl.jl_segment_7,
          sjl.jl_segment_8,
          sjl.jl_segment_9,
          sjl.jl_segment_10,
          sjl.jl_attribute_1,
          sjl.jl_attribute_2,
          sjl.jl_attribute_3,
          sjl.jl_attribute_4,
          sjl.jl_attribute_5,
          sjl.jl_reference_1,
          sjl.jl_reference_2,
          sjl.jl_reference_3,
          sjl.jl_reference_4,
          sjl.jl_reference_5,
          sjl.jl_reference_6,
          sjl.jl_reference_7,
          sjl.jl_reference_8,
          sjl.jl_reference_9,
          sjl.jl_reference_10,
          sjl.jl_tran_ccy,
          sjl.jl_tran_amount,
          sjl.jl_base_rate,
          sjl.jl_base_ccy,
          sjl.jl_base_amount,
          sjl.jl_local_rate,
          sjl.jl_local_ccy,
          sjl.jl_local_amount,
          sjl.jl_created_by,
          sjl.jl_created_on,
          sjl.jl_amended_by,
          sjl.jl_amended_on,
          sjl.jl_recon_status,
          sjl.jl_translation_date,
          sjl.jl_bus_posting_date,
          sjl.jl_period_month,
          sjl.jl_period_year,
          sjl.jl_period_ltd,
          sjl.jl_type
     FROM rdr.rr_glint_journal_line gjl
           JOIN slr.slr_jrnl_lines sjl
             ON     sjl.jl_effective_date = gjl.accounting_dt
                AND sjl.jl_tran_ccy = gjl.foreign_currency
                AND sjl.jl_base_ccy = gjl.currency_cd
                AND substr (sjl.jl_account, 1, 8) = gjl.account
                AND (CASE
                        WHEN sjl.jl_segment_3 = 'NVS' THEN ' '
                        ELSE sjl.jl_segment_3
                     END) = gjl.deptid
                AND (CASE
                        WHEN sjl.jl_segment_5 = 'NVS' THEN ' '
                        ELSE substr (sjl.jl_segment_5, 1, 10)
                     END) = gjl.chartfield1
                AND (CASE
                        WHEN sjl.jl_segment_4 = 'NVS' THEN ' '
                        ELSE sjl.jl_segment_4
                     END) = gjl.affiliate
                AND sjl.jl_entity = gjl.business_unit_gl
                AND sjl.jl_jrnl_process_id = gjl.slr_process_id
                AND sjl.jl_segment_1 = gjl.ledger_group
                AND (   (    gjl.manual_je = 'Y'
                         AND sjl.jl_jrnl_hdr_id = gjl.aah_jrnl_hdr_nbr)
                     or (gjl.manual_je = 'N' AND gjl.aah_jrnl_hdr_nbr = 0))
          JOIN fdr.fr_general_lookup fgl
             ON     sjl.jl_attribute_4 = fgl.lk_match_key1
                AND fgl.lk_lkt_lookup_type_code = 'EVENT_HIERARCHY'
                AND gjl.event_class = fgl.lk_lookup_value3
    WHERE 1 = 1;

comment on table rdr.rrv_ag_glint_ps_journals is 'View that ties PS Journals to GLINT to SLR';
