select
       acct_cd
     , ccy
     , business_unit
     , epg_id
     , fak_segment_1
     , fak_segment_2
     , fak_segment_3
     , fak_segment_4
     , fak_segment_5
     , fak_segment_6
     , fak_segment_7
     , fak_segment_8
     , fak_segment_9
     , fak_segment_10
     , eba_attribute_1
     , eba_attribute_2
     , eba_attribute_3
     , eba_attribute_4
     , eba_attribute_5
     , jl_jrnl_status
     , jl_effective_date
     , jl_value_date
     , jl_entity
     , jl_account
     , jl_segment_1
     , jl_segment_2
     , jl_segment_3
     , jl_segment_4
     , jl_segment_5
     , jl_segment_6
     , jl_segment_7
     , jl_segment_8
     , jl_segment_9
     , jl_segment_10
     , jl_attribute_1
     , jl_attribute_2
     , jl_attribute_3
     , jl_attribute_4
     , jl_attribute_5
     , jl_reference_1
     , jl_reference_2
     , jl_reference_3
     , jl_reference_4
     , jl_reference_5
     , jl_reference_6
     , jl_reference_7
     , jl_reference_8
     , jl_reference_9
     , jl_reference_10
     , jl_tran_ccy
     , jl_tran_amount
     , jl_base_rate
     , jl_base_ccy
     , jl_base_amount
     , jl_local_rate
     , jl_local_ccy
     , jl_local_amount
     , jl_period_month
     , jl_period_year
     , jl_period_ltd
     , jl_type
  from
            er_slr_jrnl_lines