create table stn.step_run
(
    step_run_sid       number generated by default as identity not null
,   step_id            number                                  not null
,   constraint pk_step_run primary key ( step_run_sid )
);